<Project>

  <PropertyGroup>
    <MajorVersion>0</MajorVersion>
    <MinorVersion>1</MinorVersion>
    <ProtocolVersion>1677763</ProtocolVersion>
    <VersionPrefix>$(MajorVersion).$(MinorVersion).$(ProtocolVersion)</VersionPrefix>
    <AssemblyVersion>$(MajorVersion).0.0.0</AssemblyVersion>
    <FileVersion>$(MajorVersion).0.0.0</FileVersion>
  </PropertyGroup>

  <PropertyGroup>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
  </PropertyGroup>

</Project>
