#nullable enable
#pragma warning disable CS0612
using global::System.Text.Json.Serialization;
using global::OpenQA.Selenium.BiDi;

namespace Selenium.WebDriver.BiDi.Cdp.Input;

/// <summary>
/// </summary>
public interface IInput
{
    /// <summary>
    /// Dispatches a drag event into the page.
    /// </summary>
    /// <param name="type">
    /// Type of the drag event.
    /// </param>
    /// <param name="x">
    /// X coordinate of the event relative to the main frame's viewport in CSS pixels.
    /// </param>
    /// <param name="y">
    /// Y coordinate of the event relative to the main frame's viewport in CSS pixels. 0 refers to
    /// the top of the viewport and Y increases as it proceeds towards the bottom of the viewport.
    /// </param>
    /// <param name="data">
    /// </param>
    /// <param name="modifiers">
    /// Bit field representing pressed modifier keys. Alt=1, Ctrl=2, Meta/Command=4, Shift=8
    /// (default: 0).
    /// </param>
    /// <param name="session">
    /// Optional CDP session override.
    /// </param>
    /// <param name="cancellationToken">
    /// A token to cancel the asynchronous operation.
    /// </param>
    /// <returns>
    /// A task representing the asynchronous operation, containing a <see cref="DispatchDragEventResult"/>.
    /// </returns>
    [global::System.Diagnostics.CodeAnalysis.Experimental("BIDICDP001")]
    Task<DispatchDragEventResult> DispatchDragEventAsync(string type, double x, double y, DragData data, long? modifiers = default, string? session = default, CancellationToken cancellationToken = default);

    /// <summary>
    /// Dispatches a key event to the page.
    /// </summary>
    /// <param name="type">
    /// Type of the key event.
    /// </param>
    /// <param name="modifiers">
    /// Bit field representing pressed modifier keys. Alt=1, Ctrl=2, Meta/Command=4, Shift=8
    /// (default: 0).
    /// </param>
    /// <param name="timestamp">
    /// Time at which the event occurred.
    /// </param>
    /// <param name="text">
    /// Text as generated by processing a virtual key code with a keyboard layout. Not needed for
    /// for <b>keyUp</b> and <b>rawKeyDown</b> events (default: "")
    /// </param>
    /// <param name="unmodifiedText">
    /// Text that would have been generated by the keyboard if no modifiers were pressed (except for
    /// shift). Useful for shortcut (accelerator) key handling (default: "").
    /// </param>
    /// <param name="keyIdentifier">
    /// Unique key identifier (e.g., 'U+0041') (default: "").
    /// </param>
    /// <param name="code">
    /// Unique DOM defined string value for each physical key (e.g., 'KeyA') (default: "").
    /// </param>
    /// <param name="key">
    /// Unique DOM defined string value describing the meaning of the key in the context of active
    /// modifiers, keyboard layout, etc (e.g., 'AltGr') (default: "").
    /// </param>
    /// <param name="windowsVirtualKeyCode">
    /// Windows virtual key code (default: 0).
    /// </param>
    /// <param name="nativeVirtualKeyCode">
    /// Native virtual key code (default: 0).
    /// </param>
    /// <param name="autoRepeat">
    /// Whether the event was generated from auto repeat (default: false).
    /// </param>
    /// <param name="isKeypad">
    /// Whether the event was generated from the keypad (default: false).
    /// </param>
    /// <param name="isSystemKey">
    /// Whether the event was a system key event (default: false).
    /// </param>
    /// <param name="location">
    /// Whether the event was from the left or right side of the keyboard. 1=Left, 2=Right (default:
    /// 0).
    /// </param>
    /// <param name="commands">
    /// Editing commands to send with the key event (e.g., 'selectAll') (default: []).
    /// These are related to but not equal the command names used in <b>document.execCommand</b> and NSStandardKeyBindingResponding.
    /// See https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/editing/commands/editor_command_names.h for valid command names.
    /// </param>
    /// <param name="session">
    /// Optional CDP session override.
    /// </param>
    /// <param name="cancellationToken">
    /// A token to cancel the asynchronous operation.
    /// </param>
    /// <returns>
    /// A task representing the asynchronous operation, containing a <see cref="DispatchKeyEventResult"/>.
    /// </returns>
    Task<DispatchKeyEventResult> DispatchKeyEventAsync(string type, long? modifiers = default, TimeSinceEpoch? timestamp = default, string? text = default, string? unmodifiedText = default, string? keyIdentifier = default, string? code = default, string? key = default, long? windowsVirtualKeyCode = default, long? nativeVirtualKeyCode = default, bool? autoRepeat = default, bool? isKeypad = default, bool? isSystemKey = default, long? location = default, ImmutableArray<string>? commands = default, string? session = default, CancellationToken cancellationToken = default);

    /// <summary>
    /// This method emulates inserting text that doesn't come from a key press,
    /// for example an emoji keyboard or an IME.
    /// </summary>
    /// <param name="text">
    /// The text to insert.
    /// </param>
    /// <param name="session">
    /// Optional CDP session override.
    /// </param>
    /// <param name="cancellationToken">
    /// A token to cancel the asynchronous operation.
    /// </param>
    /// <returns>
    /// A task representing the asynchronous operation, containing a <see cref="InsertTextResult"/>.
    /// </returns>
    [global::System.Diagnostics.CodeAnalysis.Experimental("BIDICDP001")]
    Task<InsertTextResult> InsertTextAsync(string text, string? session = default, CancellationToken cancellationToken = default);

    /// <summary>
    /// This method sets the current candidate text for IME.
    /// Use imeCommitComposition to commit the final text.
    /// Use imeSetComposition with empty string as text to cancel composition.
    /// </summary>
    /// <param name="text">
    /// The text to insert
    /// </param>
    /// <param name="selectionStart">
    /// selection start
    /// </param>
    /// <param name="selectionEnd">
    /// selection end
    /// </param>
    /// <param name="replacementStart">
    /// replacement start
    /// </param>
    /// <param name="replacementEnd">
    /// replacement end
    /// </param>
    /// <param name="session">
    /// Optional CDP session override.
    /// </param>
    /// <param name="cancellationToken">
    /// A token to cancel the asynchronous operation.
    /// </param>
    /// <returns>
    /// A task representing the asynchronous operation, containing a <see cref="ImeSetCompositionResult"/>.
    /// </returns>
    [global::System.Diagnostics.CodeAnalysis.Experimental("BIDICDP001")]
    Task<ImeSetCompositionResult> ImeSetCompositionAsync(string text, long selectionStart, long selectionEnd, long? replacementStart = default, long? replacementEnd = default, string? session = default, CancellationToken cancellationToken = default);

    /// <summary>
    /// Dispatches a mouse event to the page.
    /// </summary>
    /// <param name="type">
    /// Type of the mouse event.
    /// </param>
    /// <param name="x">
    /// X coordinate of the event relative to the main frame's viewport in CSS pixels.
    /// </param>
    /// <param name="y">
    /// Y coordinate of the event relative to the main frame's viewport in CSS pixels. 0 refers to
    /// the top of the viewport and Y increases as it proceeds towards the bottom of the viewport.
    /// </param>
    /// <param name="modifiers">
    /// Bit field representing pressed modifier keys. Alt=1, Ctrl=2, Meta/Command=4, Shift=8
    /// (default: 0).
    /// </param>
    /// <param name="timestamp">
    /// Time at which the event occurred.
    /// </param>
    /// <param name="button">
    /// Mouse button (default: "none").
    /// </param>
    /// <param name="buttons">
    /// A number indicating which buttons are pressed on the mouse when a mouse event is triggered.
    /// Left=1, Right=2, Middle=4, Back=8, Forward=16, None=0.
    /// </param>
    /// <param name="clickCount">
    /// Number of times the mouse button was clicked (default: 0).
    /// </param>
    /// <param name="force">
    /// The normalized pressure, which has a range of [0,1] (default: 0).
    /// </param>
    /// <param name="tangentialPressure">
    /// The normalized tangential pressure, which has a range of [-1,1] (default: 0).
    /// </param>
    /// <param name="tiltX">
    /// The plane angle between the Y-Z plane and the plane containing both the stylus axis and the Y axis, in degrees of the range [-90,90], a positive tiltX is to the right (default: 0).
    /// </param>
    /// <param name="tiltY">
    /// The plane angle between the X-Z plane and the plane containing both the stylus axis and the X axis, in degrees of the range [-90,90], a positive tiltY is towards the user (default: 0).
    /// </param>
    /// <param name="twist">
    /// The clockwise rotation of a pen stylus around its own major axis, in degrees in the range [0,359] (default: 0).
    /// </param>
    /// <param name="deltaX">
    /// X delta in CSS pixels for mouse wheel event (default: 0).
    /// </param>
    /// <param name="deltaY">
    /// Y delta in CSS pixels for mouse wheel event (default: 0).
    /// </param>
    /// <param name="pointerType">
    /// Pointer type (default: "mouse").
    /// </param>
    /// <param name="session">
    /// Optional CDP session override.
    /// </param>
    /// <param name="cancellationToken">
    /// A token to cancel the asynchronous operation.
    /// </param>
    /// <returns>
    /// A task representing the asynchronous operation, containing a <see cref="DispatchMouseEventResult"/>.
    /// </returns>
    Task<DispatchMouseEventResult> DispatchMouseEventAsync(string type, double x, double y, long? modifiers = default, TimeSinceEpoch? timestamp = default, MouseButton? button = default, long? buttons = default, long? clickCount = default, double? force = default, double? tangentialPressure = default, double? tiltX = default, double? tiltY = default, long? twist = default, double? deltaX = default, double? deltaY = default, string? pointerType = default, string? session = default, CancellationToken cancellationToken = default);

    /// <summary>
    /// Dispatches a touch event to the page.
    /// </summary>
    /// <param name="type">
    /// Type of the touch event. TouchEnd and TouchCancel must not contain any touch points, while
    /// TouchStart and TouchMove must contains at least one.
    /// </param>
    /// <param name="touchPoints">
    /// Active touch points on the touch device. One event per any changed point (compared to
    /// previous touch event in a sequence) is generated, emulating pressing/moving/releasing points
    /// one by one.
    /// </param>
    /// <param name="modifiers">
    /// Bit field representing pressed modifier keys. Alt=1, Ctrl=2, Meta/Command=4, Shift=8
    /// (default: 0).
    /// </param>
    /// <param name="timestamp">
    /// Time at which the event occurred.
    /// </param>
    /// <param name="session">
    /// Optional CDP session override.
    /// </param>
    /// <param name="cancellationToken">
    /// A token to cancel the asynchronous operation.
    /// </param>
    /// <returns>
    /// A task representing the asynchronous operation, containing a <see cref="DispatchTouchEventResult"/>.
    /// </returns>
    Task<DispatchTouchEventResult> DispatchTouchEventAsync(string type, ImmutableArray<TouchPoint> touchPoints, long? modifiers = default, TimeSinceEpoch? timestamp = default, string? session = default, CancellationToken cancellationToken = default);

    /// <summary>
    /// Cancels any active dragging in the page.
    /// </summary>
    /// <param name="session">
    /// Optional CDP session override.
    /// </param>
    /// <param name="cancellationToken">
    /// A token to cancel the asynchronous operation.
    /// </param>
    /// <returns>
    /// A task representing the asynchronous operation, containing a <see cref="CancelDraggingResult"/>.
    /// </returns>
    Task<CancelDraggingResult> CancelDraggingAsync(string? session = default, CancellationToken cancellationToken = default);

    /// <summary>
    /// Emulates touch event from the mouse event parameters.
    /// </summary>
    /// <param name="type">
    /// Type of the mouse event.
    /// </param>
    /// <param name="x">
    /// X coordinate of the mouse pointer in DIP.
    /// </param>
    /// <param name="y">
    /// Y coordinate of the mouse pointer in DIP.
    /// </param>
    /// <param name="button">
    /// Mouse button. Only "none", "left", "right" are supported.
    /// </param>
    /// <param name="timestamp">
    /// Time at which the event occurred (default: current time).
    /// </param>
    /// <param name="deltaX">
    /// X delta in DIP for mouse wheel event (default: 0).
    /// </param>
    /// <param name="deltaY">
    /// Y delta in DIP for mouse wheel event (default: 0).
    /// </param>
    /// <param name="modifiers">
    /// Bit field representing pressed modifier keys. Alt=1, Ctrl=2, Meta/Command=4, Shift=8
    /// (default: 0).
    /// </param>
    /// <param name="clickCount">
    /// Number of times the mouse button was clicked (default: 0).
    /// </param>
    /// <param name="session">
    /// Optional CDP session override.
    /// </param>
    /// <param name="cancellationToken">
    /// A token to cancel the asynchronous operation.
    /// </param>
    /// <returns>
    /// A task representing the asynchronous operation, containing a <see cref="EmulateTouchFromMouseEventResult"/>.
    /// </returns>
    [global::System.Diagnostics.CodeAnalysis.Experimental("BIDICDP001")]
    Task<EmulateTouchFromMouseEventResult> EmulateTouchFromMouseEventAsync(string type, long x, long y, MouseButton button, TimeSinceEpoch? timestamp = default, double? deltaX = default, double? deltaY = default, long? modifiers = default, long? clickCount = default, string? session = default, CancellationToken cancellationToken = default);

    /// <summary>
    /// Ignores input events (useful while auditing page).
    /// </summary>
    /// <param name="ignore">
    /// Ignores input events processing when set to true.
    /// </param>
    /// <param name="session">
    /// Optional CDP session override.
    /// </param>
    /// <param name="cancellationToken">
    /// A token to cancel the asynchronous operation.
    /// </param>
    /// <returns>
    /// A task representing the asynchronous operation, containing a <see cref="SetIgnoreInputEventsResult"/>.
    /// </returns>
    Task<SetIgnoreInputEventsResult> SetIgnoreInputEventsAsync(bool ignore, string? session = default, CancellationToken cancellationToken = default);

    /// <summary>
    /// Prevents default drag and drop behavior and instead emits <b>Input.dragIntercepted</b> events.
    /// Drag and drop behavior can be directly controlled via <b>Input.dispatchDragEvent</b>.
    /// </summary>
    /// <param name="enabled">
    /// </param>
    /// <param name="session">
    /// Optional CDP session override.
    /// </param>
    /// <param name="cancellationToken">
    /// A token to cancel the asynchronous operation.
    /// </param>
    /// <returns>
    /// A task representing the asynchronous operation, containing a <see cref="SetInterceptDragsResult"/>.
    /// </returns>
    [global::System.Diagnostics.CodeAnalysis.Experimental("BIDICDP001")]
    Task<SetInterceptDragsResult> SetInterceptDragsAsync(bool enabled, string? session = default, CancellationToken cancellationToken = default);

    /// <summary>
    /// Synthesizes a pinch gesture over a time period by issuing appropriate touch events.
    /// </summary>
    /// <param name="x">
    /// X coordinate of the start of the gesture in CSS pixels.
    /// </param>
    /// <param name="y">
    /// Y coordinate of the start of the gesture in CSS pixels.
    /// </param>
    /// <param name="scaleFactor">
    /// Relative scale factor after zooming (&gt;1.0 zooms in, &lt;1.0 zooms out).
    /// </param>
    /// <param name="relativeSpeed">
    /// Relative pointer speed in pixels per second (default: 800).
    /// </param>
    /// <param name="gestureSourceType">
    /// Which type of input events to be generated (default: 'default', which queries the platform
    /// for the preferred input type).
    /// </param>
    /// <param name="session">
    /// Optional CDP session override.
    /// </param>
    /// <param name="cancellationToken">
    /// A token to cancel the asynchronous operation.
    /// </param>
    /// <returns>
    /// A task representing the asynchronous operation, containing a <see cref="SynthesizePinchGestureResult"/>.
    /// </returns>
    [global::System.Diagnostics.CodeAnalysis.Experimental("BIDICDP001")]
    Task<SynthesizePinchGestureResult> SynthesizePinchGestureAsync(double x, double y, double scaleFactor, long? relativeSpeed = default, GestureSourceType? gestureSourceType = default, string? session = default, CancellationToken cancellationToken = default);

    /// <summary>
    /// Synthesizes a scroll gesture over a time period by issuing appropriate touch events.
    /// </summary>
    /// <param name="x">
    /// X coordinate of the start of the gesture in CSS pixels.
    /// </param>
    /// <param name="y">
    /// Y coordinate of the start of the gesture in CSS pixels.
    /// </param>
    /// <param name="xDistance">
    /// The distance to scroll along the X axis (positive to scroll left).
    /// </param>
    /// <param name="yDistance">
    /// The distance to scroll along the Y axis (positive to scroll up).
    /// </param>
    /// <param name="xOverscroll">
    /// The number of additional pixels to scroll back along the X axis, in addition to the given
    /// distance.
    /// </param>
    /// <param name="yOverscroll">
    /// The number of additional pixels to scroll back along the Y axis, in addition to the given
    /// distance.
    /// </param>
    /// <param name="preventFling">
    /// Prevent fling (default: true).
    /// </param>
    /// <param name="speed">
    /// Swipe speed in pixels per second (default: 800).
    /// </param>
    /// <param name="gestureSourceType">
    /// Which type of input events to be generated (default: 'default', which queries the platform
    /// for the preferred input type).
    /// </param>
    /// <param name="repeatCount">
    /// The number of times to repeat the gesture (default: 0).
    /// </param>
    /// <param name="repeatDelayMs">
    /// The number of milliseconds delay between each repeat. (default: 250).
    /// </param>
    /// <param name="interactionMarkerName">
    /// The name of the interaction markers to generate, if not empty (default: "").
    /// </param>
    /// <param name="session">
    /// Optional CDP session override.
    /// </param>
    /// <param name="cancellationToken">
    /// A token to cancel the asynchronous operation.
    /// </param>
    /// <returns>
    /// A task representing the asynchronous operation, containing a <see cref="SynthesizeScrollGestureResult"/>.
    /// </returns>
    [global::System.Diagnostics.CodeAnalysis.Experimental("BIDICDP001")]
    Task<SynthesizeScrollGestureResult> SynthesizeScrollGestureAsync(double x, double y, double? xDistance = default, double? yDistance = default, double? xOverscroll = default, double? yOverscroll = default, bool? preventFling = default, long? speed = default, GestureSourceType? gestureSourceType = default, long? repeatCount = default, long? repeatDelayMs = default, string? interactionMarkerName = default, string? session = default, CancellationToken cancellationToken = default);

    /// <summary>
    /// Synthesizes a tap gesture over a time period by issuing appropriate touch events.
    /// </summary>
    /// <param name="x">
    /// X coordinate of the start of the gesture in CSS pixels.
    /// </param>
    /// <param name="y">
    /// Y coordinate of the start of the gesture in CSS pixels.
    /// </param>
    /// <param name="duration">
    /// Duration between touchdown and touchup events in ms (default: 50).
    /// </param>
    /// <param name="tapCount">
    /// Number of times to perform the tap (e.g. 2 for double tap, default: 1).
    /// </param>
    /// <param name="gestureSourceType">
    /// Which type of input events to be generated (default: 'default', which queries the platform
    /// for the preferred input type).
    /// </param>
    /// <param name="session">
    /// Optional CDP session override.
    /// </param>
    /// <param name="cancellationToken">
    /// A token to cancel the asynchronous operation.
    /// </param>
    /// <returns>
    /// A task representing the asynchronous operation, containing a <see cref="SynthesizeTapGestureResult"/>.
    /// </returns>
    [global::System.Diagnostics.CodeAnalysis.Experimental("BIDICDP001")]
    Task<SynthesizeTapGestureResult> SynthesizeTapGestureAsync(double x, double y, long? duration = default, long? tapCount = default, GestureSourceType? gestureSourceType = default, string? session = default, CancellationToken cancellationToken = default);

    /// <summary>
    /// Emitted only when <b>Input.setInterceptDrags</b> is enabled. Use this data with <b>Input.dispatchDragEvent</b> to
    /// restore normal drag and drop behavior.
    /// </summary>
    /// <remarks>
    /// Event args (<see cref="DragInterceptedEventArgs"/>):
    /// <list type="bullet">
    /// <item><description><b>Data</b></description></item>
    /// </list>
    /// </remarks>
    [global::System.Diagnostics.CodeAnalysis.Experimental("BIDICDP001")]
    IEventSource<DragInterceptedEventArgs> DragIntercepted { get; }

}

internal sealed class InputDomain(CdpModule cdp) : global::Selenium.WebDriver.BiDi.Cdp.Domain(cdp), IInput
{
    private static InputJsonSerializerContext JsonContext = InputJsonSerializerContext.Default;

    [global::System.Diagnostics.CodeAnalysis.Experimental("BIDICDP001")]
    public async Task<DispatchDragEventResult> DispatchDragEventAsync(string type, double x, double y, DragData data, long? modifiers = default, string? session = default, CancellationToken cancellationToken = default)
    {
        var @params = new DispatchDragEventCommandParameters(Type: type, X: x, Y: y, Data: data, Modifiers: modifiers);
        return await ExecuteCommandAsync(DispatchDragEventCommand, @params, session, cancellationToken).ConfigureAwait(false);
    }
    private static readonly CdpCommand<DispatchDragEventCommandParameters, DispatchDragEventResult> DispatchDragEventCommand = new("Input.dispatchDragEvent", JsonContext.DispatchDragEventCommandParameters, JsonContext.DispatchDragEventResult);

    public async Task<DispatchKeyEventResult> DispatchKeyEventAsync(string type, long? modifiers = default, TimeSinceEpoch? timestamp = default, string? text = default, string? unmodifiedText = default, string? keyIdentifier = default, string? code = default, string? key = default, long? windowsVirtualKeyCode = default, long? nativeVirtualKeyCode = default, bool? autoRepeat = default, bool? isKeypad = default, bool? isSystemKey = default, long? location = default, ImmutableArray<string>? commands = default, string? session = default, CancellationToken cancellationToken = default)
    {
        var @params = new DispatchKeyEventCommandParameters(Type: type, Modifiers: modifiers, Timestamp: timestamp, Text: text, UnmodifiedText: unmodifiedText, KeyIdentifier: keyIdentifier, Code: code, Key: key, WindowsVirtualKeyCode: windowsVirtualKeyCode, NativeVirtualKeyCode: nativeVirtualKeyCode, AutoRepeat: autoRepeat, IsKeypad: isKeypad, IsSystemKey: isSystemKey, Location: location, Commands: commands);
        return await ExecuteCommandAsync(DispatchKeyEventCommand, @params, session, cancellationToken).ConfigureAwait(false);
    }
    private static readonly CdpCommand<DispatchKeyEventCommandParameters, DispatchKeyEventResult> DispatchKeyEventCommand = new("Input.dispatchKeyEvent", JsonContext.DispatchKeyEventCommandParameters, JsonContext.DispatchKeyEventResult);

    [global::System.Diagnostics.CodeAnalysis.Experimental("BIDICDP001")]
    public async Task<InsertTextResult> InsertTextAsync(string text, string? session = default, CancellationToken cancellationToken = default)
    {
        var @params = new InsertTextCommandParameters(Text: text);
        return await ExecuteCommandAsync(InsertTextCommand, @params, session, cancellationToken).ConfigureAwait(false);
    }
    private static readonly CdpCommand<InsertTextCommandParameters, InsertTextResult> InsertTextCommand = new("Input.insertText", JsonContext.InsertTextCommandParameters, JsonContext.InsertTextResult);

    [global::System.Diagnostics.CodeAnalysis.Experimental("BIDICDP001")]
    public async Task<ImeSetCompositionResult> ImeSetCompositionAsync(string text, long selectionStart, long selectionEnd, long? replacementStart = default, long? replacementEnd = default, string? session = default, CancellationToken cancellationToken = default)
    {
        var @params = new ImeSetCompositionCommandParameters(Text: text, SelectionStart: selectionStart, SelectionEnd: selectionEnd, ReplacementStart: replacementStart, ReplacementEnd: replacementEnd);
        return await ExecuteCommandAsync(ImeSetCompositionCommand, @params, session, cancellationToken).ConfigureAwait(false);
    }
    private static readonly CdpCommand<ImeSetCompositionCommandParameters, ImeSetCompositionResult> ImeSetCompositionCommand = new("Input.imeSetComposition", JsonContext.ImeSetCompositionCommandParameters, JsonContext.ImeSetCompositionResult);

    public async Task<DispatchMouseEventResult> DispatchMouseEventAsync(string type, double x, double y, long? modifiers = default, TimeSinceEpoch? timestamp = default, MouseButton? button = default, long? buttons = default, long? clickCount = default, double? force = default, double? tangentialPressure = default, double? tiltX = default, double? tiltY = default, long? twist = default, double? deltaX = default, double? deltaY = default, string? pointerType = default, string? session = default, CancellationToken cancellationToken = default)
    {
        var @params = new DispatchMouseEventCommandParameters(Type: type, X: x, Y: y, Modifiers: modifiers, Timestamp: timestamp, Button: button, Buttons: buttons, ClickCount: clickCount, Force: force, TangentialPressure: tangentialPressure, TiltX: tiltX, TiltY: tiltY, Twist: twist, DeltaX: deltaX, DeltaY: deltaY, PointerType: pointerType);
        return await ExecuteCommandAsync(DispatchMouseEventCommand, @params, session, cancellationToken).ConfigureAwait(false);
    }
    private static readonly CdpCommand<DispatchMouseEventCommandParameters, DispatchMouseEventResult> DispatchMouseEventCommand = new("Input.dispatchMouseEvent", JsonContext.DispatchMouseEventCommandParameters, JsonContext.DispatchMouseEventResult);

    public async Task<DispatchTouchEventResult> DispatchTouchEventAsync(string type, ImmutableArray<TouchPoint> touchPoints, long? modifiers = default, TimeSinceEpoch? timestamp = default, string? session = default, CancellationToken cancellationToken = default)
    {
        var @params = new DispatchTouchEventCommandParameters(Type: type, TouchPoints: touchPoints, Modifiers: modifiers, Timestamp: timestamp);
        return await ExecuteCommandAsync(DispatchTouchEventCommand, @params, session, cancellationToken).ConfigureAwait(false);
    }
    private static readonly CdpCommand<DispatchTouchEventCommandParameters, DispatchTouchEventResult> DispatchTouchEventCommand = new("Input.dispatchTouchEvent", JsonContext.DispatchTouchEventCommandParameters, JsonContext.DispatchTouchEventResult);

    public async Task<CancelDraggingResult> CancelDraggingAsync(string? session = default, CancellationToken cancellationToken = default)
    {
        var @params = new CancelDraggingCommandParameters();
        return await ExecuteCommandAsync(CancelDraggingCommand, @params, session, cancellationToken).ConfigureAwait(false);
    }
    private static readonly CdpCommand<CancelDraggingCommandParameters, CancelDraggingResult> CancelDraggingCommand = new("Input.cancelDragging", JsonContext.CancelDraggingCommandParameters, JsonContext.CancelDraggingResult);

    [global::System.Diagnostics.CodeAnalysis.Experimental("BIDICDP001")]
    public async Task<EmulateTouchFromMouseEventResult> EmulateTouchFromMouseEventAsync(string type, long x, long y, MouseButton button, TimeSinceEpoch? timestamp = default, double? deltaX = default, double? deltaY = default, long? modifiers = default, long? clickCount = default, string? session = default, CancellationToken cancellationToken = default)
    {
        var @params = new EmulateTouchFromMouseEventCommandParameters(Type: type, X: x, Y: y, Button: button, Timestamp: timestamp, DeltaX: deltaX, DeltaY: deltaY, Modifiers: modifiers, ClickCount: clickCount);
        return await ExecuteCommandAsync(EmulateTouchFromMouseEventCommand, @params, session, cancellationToken).ConfigureAwait(false);
    }
    private static readonly CdpCommand<EmulateTouchFromMouseEventCommandParameters, EmulateTouchFromMouseEventResult> EmulateTouchFromMouseEventCommand = new("Input.emulateTouchFromMouseEvent", JsonContext.EmulateTouchFromMouseEventCommandParameters, JsonContext.EmulateTouchFromMouseEventResult);

    public async Task<SetIgnoreInputEventsResult> SetIgnoreInputEventsAsync(bool ignore, string? session = default, CancellationToken cancellationToken = default)
    {
        var @params = new SetIgnoreInputEventsCommandParameters(Ignore: ignore);
        return await ExecuteCommandAsync(SetIgnoreInputEventsCommand, @params, session, cancellationToken).ConfigureAwait(false);
    }
    private static readonly CdpCommand<SetIgnoreInputEventsCommandParameters, SetIgnoreInputEventsResult> SetIgnoreInputEventsCommand = new("Input.setIgnoreInputEvents", JsonContext.SetIgnoreInputEventsCommandParameters, JsonContext.SetIgnoreInputEventsResult);

    [global::System.Diagnostics.CodeAnalysis.Experimental("BIDICDP001")]
    public async Task<SetInterceptDragsResult> SetInterceptDragsAsync(bool enabled, string? session = default, CancellationToken cancellationToken = default)
    {
        var @params = new SetInterceptDragsCommandParameters(Enabled: enabled);
        return await ExecuteCommandAsync(SetInterceptDragsCommand, @params, session, cancellationToken).ConfigureAwait(false);
    }
    private static readonly CdpCommand<SetInterceptDragsCommandParameters, SetInterceptDragsResult> SetInterceptDragsCommand = new("Input.setInterceptDrags", JsonContext.SetInterceptDragsCommandParameters, JsonContext.SetInterceptDragsResult);

    [global::System.Diagnostics.CodeAnalysis.Experimental("BIDICDP001")]
    public async Task<SynthesizePinchGestureResult> SynthesizePinchGestureAsync(double x, double y, double scaleFactor, long? relativeSpeed = default, GestureSourceType? gestureSourceType = default, string? session = default, CancellationToken cancellationToken = default)
    {
        var @params = new SynthesizePinchGestureCommandParameters(X: x, Y: y, ScaleFactor: scaleFactor, RelativeSpeed: relativeSpeed, GestureSourceType: gestureSourceType);
        return await ExecuteCommandAsync(SynthesizePinchGestureCommand, @params, session, cancellationToken).ConfigureAwait(false);
    }
    private static readonly CdpCommand<SynthesizePinchGestureCommandParameters, SynthesizePinchGestureResult> SynthesizePinchGestureCommand = new("Input.synthesizePinchGesture", JsonContext.SynthesizePinchGestureCommandParameters, JsonContext.SynthesizePinchGestureResult);

    [global::System.Diagnostics.CodeAnalysis.Experimental("BIDICDP001")]
    public async Task<SynthesizeScrollGestureResult> SynthesizeScrollGestureAsync(double x, double y, double? xDistance = default, double? yDistance = default, double? xOverscroll = default, double? yOverscroll = default, bool? preventFling = default, long? speed = default, GestureSourceType? gestureSourceType = default, long? repeatCount = default, long? repeatDelayMs = default, string? interactionMarkerName = default, string? session = default, CancellationToken cancellationToken = default)
    {
        var @params = new SynthesizeScrollGestureCommandParameters(X: x, Y: y, XDistance: xDistance, YDistance: yDistance, XOverscroll: xOverscroll, YOverscroll: yOverscroll, PreventFling: preventFling, Speed: speed, GestureSourceType: gestureSourceType, RepeatCount: repeatCount, RepeatDelayMs: repeatDelayMs, InteractionMarkerName: interactionMarkerName);
        return await ExecuteCommandAsync(SynthesizeScrollGestureCommand, @params, session, cancellationToken).ConfigureAwait(false);
    }
    private static readonly CdpCommand<SynthesizeScrollGestureCommandParameters, SynthesizeScrollGestureResult> SynthesizeScrollGestureCommand = new("Input.synthesizeScrollGesture", JsonContext.SynthesizeScrollGestureCommandParameters, JsonContext.SynthesizeScrollGestureResult);

    [global::System.Diagnostics.CodeAnalysis.Experimental("BIDICDP001")]
    public async Task<SynthesizeTapGestureResult> SynthesizeTapGestureAsync(double x, double y, long? duration = default, long? tapCount = default, GestureSourceType? gestureSourceType = default, string? session = default, CancellationToken cancellationToken = default)
    {
        var @params = new SynthesizeTapGestureCommandParameters(X: x, Y: y, Duration: duration, TapCount: tapCount, GestureSourceType: gestureSourceType);
        return await ExecuteCommandAsync(SynthesizeTapGestureCommand, @params, session, cancellationToken).ConfigureAwait(false);
    }
    private static readonly CdpCommand<SynthesizeTapGestureCommandParameters, SynthesizeTapGestureResult> SynthesizeTapGestureCommand = new("Input.synthesizeTapGesture", JsonContext.SynthesizeTapGestureCommandParameters, JsonContext.SynthesizeTapGestureResult);

    [global::System.Diagnostics.CodeAnalysis.Experimental("BIDICDP001")]
    public IEventSource<DragInterceptedEventArgs> DragIntercepted => CreateCdpEventSource(InputDomainEvent.DragIntercepted);
}

internal sealed record DispatchDragEventCommandParameters(string Type, double X, double Y, DragData Data, long? Modifiers) : Parameters;

/// <summary>
/// </summary>
public sealed record DispatchDragEventResult() : EmptyResult;


internal sealed record DispatchKeyEventCommandParameters(string Type, long? Modifiers, TimeSinceEpoch? Timestamp, string? Text, string? UnmodifiedText, string? KeyIdentifier, string? Code, string? Key, long? WindowsVirtualKeyCode, long? NativeVirtualKeyCode, bool? AutoRepeat, bool? IsKeypad, bool? IsSystemKey, long? Location, ImmutableArray<string>? Commands) : Parameters;

/// <summary>
/// </summary>
public sealed record DispatchKeyEventResult() : EmptyResult;


internal sealed record InsertTextCommandParameters(string Text) : Parameters;

/// <summary>
/// </summary>
public sealed record InsertTextResult() : EmptyResult;


internal sealed record ImeSetCompositionCommandParameters(string Text, long SelectionStart, long SelectionEnd, long? ReplacementStart, long? ReplacementEnd) : Parameters;

/// <summary>
/// </summary>
public sealed record ImeSetCompositionResult() : EmptyResult;


internal sealed record DispatchMouseEventCommandParameters(string Type, double X, double Y, long? Modifiers, TimeSinceEpoch? Timestamp, MouseButton? Button, long? Buttons, long? ClickCount, double? Force, double? TangentialPressure, double? TiltX, double? TiltY, long? Twist, double? DeltaX, double? DeltaY, string? PointerType) : Parameters;

/// <summary>
/// </summary>
public sealed record DispatchMouseEventResult() : EmptyResult;


internal sealed record DispatchTouchEventCommandParameters(string Type, ImmutableArray<TouchPoint> TouchPoints, long? Modifiers, TimeSinceEpoch? Timestamp) : Parameters;

/// <summary>
/// </summary>
public sealed record DispatchTouchEventResult() : EmptyResult;


internal sealed record CancelDraggingCommandParameters() : Parameters;

/// <summary>
/// </summary>
public sealed record CancelDraggingResult() : EmptyResult;


internal sealed record EmulateTouchFromMouseEventCommandParameters(string Type, long X, long Y, MouseButton Button, TimeSinceEpoch? Timestamp, double? DeltaX, double? DeltaY, long? Modifiers, long? ClickCount) : Parameters;

/// <summary>
/// </summary>
public sealed record EmulateTouchFromMouseEventResult() : EmptyResult;


internal sealed record SetIgnoreInputEventsCommandParameters(bool Ignore) : Parameters;

/// <summary>
/// </summary>
public sealed record SetIgnoreInputEventsResult() : EmptyResult;


internal sealed record SetInterceptDragsCommandParameters(bool Enabled) : Parameters;

/// <summary>
/// </summary>
public sealed record SetInterceptDragsResult() : EmptyResult;


internal sealed record SynthesizePinchGestureCommandParameters(double X, double Y, double ScaleFactor, long? RelativeSpeed, GestureSourceType? GestureSourceType) : Parameters;

/// <summary>
/// </summary>
public sealed record SynthesizePinchGestureResult() : EmptyResult;


internal sealed record SynthesizeScrollGestureCommandParameters(double X, double Y, double? XDistance, double? YDistance, double? XOverscroll, double? YOverscroll, bool? PreventFling, long? Speed, GestureSourceType? GestureSourceType, long? RepeatCount, long? RepeatDelayMs, string? InteractionMarkerName) : Parameters;

/// <summary>
/// </summary>
public sealed record SynthesizeScrollGestureResult() : EmptyResult;


internal sealed record SynthesizeTapGestureCommandParameters(double X, double Y, long? Duration, long? TapCount, GestureSourceType? GestureSourceType) : Parameters;

/// <summary>
/// </summary>
public sealed record SynthesizeTapGestureResult() : EmptyResult;


/// <summary>
/// Emitted only when <b>Input.setInterceptDrags</b> is enabled. Use this data with <b>Input.dispatchDragEvent</b> to
/// restore normal drag and drop behavior.
/// </summary>
/// <param name="Data">
/// </param>
public sealed record DragInterceptedEventArgs(DragData Data) : OpenQA.Selenium.BiDi.EventArgs;

/// <summary>
/// </summary>
/// <param name="X">
/// X coordinate of the event relative to the main frame's viewport in CSS pixels.
/// </param>
/// <param name="Y">
/// Y coordinate of the event relative to the main frame's viewport in CSS pixels. 0 refers to
/// the top of the viewport and Y increases as it proceeds towards the bottom of the viewport.
/// </param>
public sealed record TouchPoint(double X, double Y)
{
    /// <summary>
    /// X radius of the touch area (default: 1.0).
    /// </summary>
    public double? RadiusX { get; init; }

    /// <summary>
    /// Y radius of the touch area (default: 1.0).
    /// </summary>
    public double? RadiusY { get; init; }

    /// <summary>
    /// Rotation angle (default: 0.0).
    /// </summary>
    public double? RotationAngle { get; init; }

    /// <summary>
    /// Force (default: 1.0).
    /// </summary>
    public double? Force { get; init; }

    /// <summary>
    /// The normalized tangential pressure, which has a range of [-1,1] (default: 0).
    /// </summary>
    public double? TangentialPressure { get; init; }

    /// <summary>
    /// The plane angle between the Y-Z plane and the plane containing both the stylus axis and the Y axis, in degrees of the range [-90,90], a positive tiltX is to the right (default: 0)
    /// </summary>
    public double? TiltX { get; init; }

    /// <summary>
    /// The plane angle between the X-Z plane and the plane containing both the stylus axis and the X axis, in degrees of the range [-90,90], a positive tiltY is towards the user (default: 0).
    /// </summary>
    public double? TiltY { get; init; }

    /// <summary>
    /// The clockwise rotation of a pen stylus around its own major axis, in degrees in the range [0,359] (default: 0).
    /// </summary>
    public long? Twist { get; init; }

    /// <summary>
    /// Identifier used to track touch sources between events, must be unique within an event.
    /// </summary>
    public double? Id { get; init; }
}

/// <summary>
/// </summary>
[global::System.Text.Json.Serialization.JsonConverter(typeof(Json.JsonStringEnumConverter<GestureSourceType>))]
public enum GestureSourceType
{
    /// <summary>
    /// </summary>
    [global::System.Text.Json.Serialization.JsonStringEnumMemberName("default")]
    Default,
    /// <summary>
    /// </summary>
    [global::System.Text.Json.Serialization.JsonStringEnumMemberName("touch")]
    Touch,
    /// <summary>
    /// </summary>
    [global::System.Text.Json.Serialization.JsonStringEnumMemberName("mouse")]
    Mouse,
}

/// <summary>
/// </summary>
[global::System.Text.Json.Serialization.JsonConverter(typeof(Json.JsonStringEnumConverter<MouseButton>))]
public enum MouseButton
{
    /// <summary>
    /// </summary>
    [global::System.Text.Json.Serialization.JsonStringEnumMemberName("none")]
    None,
    /// <summary>
    /// </summary>
    [global::System.Text.Json.Serialization.JsonStringEnumMemberName("left")]
    Left,
    /// <summary>
    /// </summary>
    [global::System.Text.Json.Serialization.JsonStringEnumMemberName("middle")]
    Middle,
    /// <summary>
    /// </summary>
    [global::System.Text.Json.Serialization.JsonStringEnumMemberName("right")]
    Right,
    /// <summary>
    /// </summary>
    [global::System.Text.Json.Serialization.JsonStringEnumMemberName("back")]
    Back,
    /// <summary>
    /// </summary>
    [global::System.Text.Json.Serialization.JsonStringEnumMemberName("forward")]
    Forward,
}

/// <summary>
/// UTC time in seconds, counted from January 1, 1970.
/// </summary>
[global::System.Text.Json.Serialization.JsonConverter(typeof(Json.NumberRemoteIdConverter<TimeSinceEpoch>))]
public record TimeSinceEpoch : INumberRemoteId
{
    double INumberRemoteId.Id { get; init; }
}

/// <summary>
/// </summary>
/// <param name="MimeType">
/// Mime type of the dragged data.
/// </param>
/// <param name="Data">
/// Depending of the value of <b>mimeType</b>, it contains the dragged link,
/// text, HTML markup or any other data.
/// </param>
public sealed record DragDataItem(string MimeType, string Data)
{
    /// <summary>
    /// Title associated with a link. Only valid when <b>mimeType</b> == "text/uri-list".
    /// </summary>
    public string? Title { get; init; }

    /// <summary>
    /// Stores the base URL for the contained markup. Only valid when <b>mimeType</b>
    /// == "text/html".
    /// </summary>
    public string? BaseURL { get; init; }
}

/// <summary>
/// </summary>
/// <param name="Items">
/// </param>
/// <param name="DragOperationsMask">
/// Bit field representing allowed drag operations. Copy = 1, Link = 2, Move = 16
/// </param>
public sealed record DragData(ImmutableArray<DragDataItem> Items, long DragOperationsMask)
{
    /// <summary>
    /// List of filenames that should be included when dropping
    /// </summary>
    public ImmutableArray<string>? Files { get; init; }
}

[JsonSerializable(typeof(DispatchDragEventCommandParameters), TypeInfoPropertyName = "DispatchDragEventCommandParameters")]
[JsonSerializable(typeof(DispatchDragEventResult), TypeInfoPropertyName = "DispatchDragEventResult")]
[JsonSerializable(typeof(DispatchKeyEventCommandParameters), TypeInfoPropertyName = "DispatchKeyEventCommandParameters")]
[JsonSerializable(typeof(DispatchKeyEventResult), TypeInfoPropertyName = "DispatchKeyEventResult")]
[JsonSerializable(typeof(InsertTextCommandParameters), TypeInfoPropertyName = "InsertTextCommandParameters")]
[JsonSerializable(typeof(InsertTextResult), TypeInfoPropertyName = "InsertTextResult")]
[JsonSerializable(typeof(ImeSetCompositionCommandParameters), TypeInfoPropertyName = "ImeSetCompositionCommandParameters")]
[JsonSerializable(typeof(ImeSetCompositionResult), TypeInfoPropertyName = "ImeSetCompositionResult")]
[JsonSerializable(typeof(DispatchMouseEventCommandParameters), TypeInfoPropertyName = "DispatchMouseEventCommandParameters")]
[JsonSerializable(typeof(DispatchMouseEventResult), TypeInfoPropertyName = "DispatchMouseEventResult")]
[JsonSerializable(typeof(DispatchTouchEventCommandParameters), TypeInfoPropertyName = "DispatchTouchEventCommandParameters")]
[JsonSerializable(typeof(DispatchTouchEventResult), TypeInfoPropertyName = "DispatchTouchEventResult")]
[JsonSerializable(typeof(CancelDraggingCommandParameters), TypeInfoPropertyName = "CancelDraggingCommandParameters")]
[JsonSerializable(typeof(CancelDraggingResult), TypeInfoPropertyName = "CancelDraggingResult")]
[JsonSerializable(typeof(EmulateTouchFromMouseEventCommandParameters), TypeInfoPropertyName = "EmulateTouchFromMouseEventCommandParameters")]
[JsonSerializable(typeof(EmulateTouchFromMouseEventResult), TypeInfoPropertyName = "EmulateTouchFromMouseEventResult")]
[JsonSerializable(typeof(SetIgnoreInputEventsCommandParameters), TypeInfoPropertyName = "SetIgnoreInputEventsCommandParameters")]
[JsonSerializable(typeof(SetIgnoreInputEventsResult), TypeInfoPropertyName = "SetIgnoreInputEventsResult")]
[JsonSerializable(typeof(SetInterceptDragsCommandParameters), TypeInfoPropertyName = "SetInterceptDragsCommandParameters")]
[JsonSerializable(typeof(SetInterceptDragsResult), TypeInfoPropertyName = "SetInterceptDragsResult")]
[JsonSerializable(typeof(SynthesizePinchGestureCommandParameters), TypeInfoPropertyName = "SynthesizePinchGestureCommandParameters")]
[JsonSerializable(typeof(SynthesizePinchGestureResult), TypeInfoPropertyName = "SynthesizePinchGestureResult")]
[JsonSerializable(typeof(SynthesizeScrollGestureCommandParameters), TypeInfoPropertyName = "SynthesizeScrollGestureCommandParameters")]
[JsonSerializable(typeof(SynthesizeScrollGestureResult), TypeInfoPropertyName = "SynthesizeScrollGestureResult")]
[JsonSerializable(typeof(SynthesizeTapGestureCommandParameters), TypeInfoPropertyName = "SynthesizeTapGestureCommandParameters")]
[JsonSerializable(typeof(SynthesizeTapGestureResult), TypeInfoPropertyName = "SynthesizeTapGestureResult")]
[JsonSerializable(typeof(CdpEventArgs<DragInterceptedEventArgs>), TypeInfoPropertyName = "DragInterceptedCdpEventArgs")]
[JsonSerializable(typeof(TouchPoint), TypeInfoPropertyName = "InputTouchPoint")]
[JsonSerializable(typeof(GestureSourceType), TypeInfoPropertyName = "InputGestureSourceType")]
[JsonSerializable(typeof(MouseButton), TypeInfoPropertyName = "InputMouseButton")]
[JsonSerializable(typeof(TimeSinceEpoch), TypeInfoPropertyName = "InputTimeSinceEpoch")]
[JsonSerializable(typeof(DragDataItem), TypeInfoPropertyName = "InputDragDataItem")]
[JsonSerializable(typeof(DragData), TypeInfoPropertyName = "InputDragData")]
[JsonSerializable(typeof(ImmutableArray<TouchPoint>), TypeInfoPropertyName = "ImmutableArrayInputTouchPoint")]
[JsonSerializable(typeof(ImmutableArray<DragDataItem>), TypeInfoPropertyName = "ImmutableArrayInputDragDataItem")]
[JsonSourceGenerationOptions(
PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
partial class InputJsonSerializerContext : JsonSerializerContext;

/// <summary>
/// Provides static event descriptors for the <see cref="IInput"/>.
/// </summary>
public static class InputDomainEvent
{
    /// <summary>
    /// Emitted only when <b>Input.setInterceptDrags</b> is enabled. Use this data with <b>Input.dispatchDragEvent</b> to
    /// restore normal drag and drop behavior.
    /// </summary>
    public static EventDescriptor<CdpEventArgs<DragInterceptedEventArgs>> DragIntercepted { get; } =
        EventDescriptor<CdpEventArgs<DragInterceptedEventArgs>>.Create(
            "goog:cdp.Input.dragIntercepted",
            InputJsonSerializerContext.Default.DragInterceptedCdpEventArgs);

}
