#nullable enable
#pragma warning disable CS0612
using global::System.Text.Json.Serialization;
using global::OpenQA.Selenium.BiDi;

namespace Selenium.WebDriver.BiDi.Cdp.Input;

/// <summary>
/// </summary>
public sealed class InputDomain(CdpModule cdp) : global::Selenium.WebDriver.BiDi.Cdp.Domain(cdp)
{
    private static InputJsonSerializerContext JsonContext = InputJsonSerializerContext.Default;

    /// <summary>
    /// Dispatches a drag event into the page.
    /// </summary>
    /// <remarks>
    /// Optional parameters (via <paramref name="options"/>):
    /// <list type="bullet">
    /// <item><description><b>Modifiers</b> - Bit field representing pressed modifier keys. Alt=1, Ctrl=2, Meta/Command=4, Shift=8 (default: 0).</description></item>
    /// </list>
    /// </remarks>
    /// <param name="type">
    /// Type of the drag event.
    /// </param>
    /// <param name="x">
    /// X coordinate of the event relative to the main frame's viewport in CSS pixels.
    /// </param>
    /// <param name="y">
    /// Y coordinate of the event relative to the main frame's viewport in CSS pixels. 0 refers to
    /// the top of the viewport and Y increases as it proceeds towards the bottom of the viewport.
    /// </param>
    /// <param name="data">
    /// </param>
    /// <param name="options">
    /// Optional parameters. See <see cref="DispatchDragEventCommandOptions"/>.
    /// </param>
    /// <param name="cancellationToken">
    /// A token to cancel the asynchronous operation.
    /// </param>
    /// <returns>
    /// A task representing the asynchronous operation, containing a <see cref="DispatchDragEventResult"/>.
    /// </returns>
    [global::System.Diagnostics.CodeAnalysis.Experimental("BIDICDP001")]
    public async Task<DispatchDragEventResult> DispatchDragEventAsync(string type, double x, double y, DragData data, DispatchDragEventCommandOptions? options = default, CancellationToken cancellationToken = default)
    {
        var @params = new DispatchDragEventCommandParameters(Type: type, X: x, Y: y, Data: data, Modifiers: options?.Modifiers);
        return await ExecuteCommandAsync(DispatchDragEventCommand, @params, options, cancellationToken).ConfigureAwait(false);
    }
    private static readonly CdpCommand<DispatchDragEventCommandParameters, DispatchDragEventResult> DispatchDragEventCommand = new("Input.dispatchDragEvent", JsonContext.DispatchDragEventCommandParameters, JsonContext.DispatchDragEventResult);

    /// <summary>
    /// Dispatches a key event to the page.
    /// </summary>
    /// <remarks>
    /// Optional parameters (via <paramref name="options"/>):
    /// <list type="bullet">
    /// <item><description><b>Modifiers</b> - Bit field representing pressed modifier keys. Alt=1, Ctrl=2, Meta/Command=4, Shift=8 (default: 0).</description></item>
    /// <item><description><b>Timestamp</b> - Time at which the event occurred.</description></item>
    /// <item><description><b>Text</b> - Text as generated by processing a virtual key code with a keyboard layout. Not needed for for <b>keyUp</b> and <b>rawKeyDown</b> events (default: "")</description></item>
    /// <item><description><b>UnmodifiedText</b> - Text that would have been generated by the keyboard if no modifiers were pressed (except for shift). Useful for shortcut (accelerator) key handling (default: "").</description></item>
    /// <item><description><b>KeyIdentifier</b> - Unique key identifier (e.g., 'U+0041') (default: "").</description></item>
    /// <item><description><b>Code</b> - Unique DOM defined string value for each physical key (e.g., 'KeyA') (default: "").</description></item>
    /// <item><description><b>Key</b> - Unique DOM defined string value describing the meaning of the key in the context of active modifiers, keyboard layout, etc (e.g., 'AltGr') (default: "").</description></item>
    /// <item><description><b>WindowsVirtualKeyCode</b> - Windows virtual key code (default: 0).</description></item>
    /// <item><description><b>NativeVirtualKeyCode</b> - Native virtual key code (default: 0).</description></item>
    /// <item><description><b>AutoRepeat</b> - Whether the event was generated from auto repeat (default: false).</description></item>
    /// <item><description><b>IsKeypad</b> - Whether the event was generated from the keypad (default: false).</description></item>
    /// <item><description><b>IsSystemKey</b> - Whether the event was a system key event (default: false).</description></item>
    /// <item><description><b>Location</b> - Whether the event was from the left or right side of the keyboard. 1=Left, 2=Right (default: 0).</description></item>
    /// <item><description><b>Commands</b> - Editing commands to send with the key event (e.g., 'selectAll') (default: []). These are related to but not equal the command names used in <b>document.execCommand</b> and NSStandardKeyBindingResponding. See https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/editing/commands/editor_command_names.h for valid command names.</description></item>
    /// </list>
    /// </remarks>
    /// <param name="type">
    /// Type of the key event.
    /// </param>
    /// <param name="options">
    /// Optional parameters. See <see cref="DispatchKeyEventCommandOptions"/>.
    /// </param>
    /// <param name="cancellationToken">
    /// A token to cancel the asynchronous operation.
    /// </param>
    /// <returns>
    /// A task representing the asynchronous operation, containing a <see cref="DispatchKeyEventResult"/>.
    /// </returns>
    public async Task<DispatchKeyEventResult> DispatchKeyEventAsync(string type, DispatchKeyEventCommandOptions? options = default, CancellationToken cancellationToken = default)
    {
        var @params = new DispatchKeyEventCommandParameters(Type: type, Modifiers: options?.Modifiers, Timestamp: options?.Timestamp, Text: options?.Text, UnmodifiedText: options?.UnmodifiedText, KeyIdentifier: options?.KeyIdentifier, Code: options?.Code, Key: options?.Key, WindowsVirtualKeyCode: options?.WindowsVirtualKeyCode, NativeVirtualKeyCode: options?.NativeVirtualKeyCode, AutoRepeat: options?.AutoRepeat, IsKeypad: options?.IsKeypad, IsSystemKey: options?.IsSystemKey, Location: options?.Location, Commands: options?.Commands);
        return await ExecuteCommandAsync(DispatchKeyEventCommand, @params, options, cancellationToken).ConfigureAwait(false);
    }
    private static readonly CdpCommand<DispatchKeyEventCommandParameters, DispatchKeyEventResult> DispatchKeyEventCommand = new("Input.dispatchKeyEvent", JsonContext.DispatchKeyEventCommandParameters, JsonContext.DispatchKeyEventResult);

    /// <summary>
    /// This method emulates inserting text that doesn't come from a key press,
    /// for example an emoji keyboard or an IME.
    /// </summary>
    /// <param name="text">
    /// The text to insert.
    /// </param>
    /// <param name="options">
    /// Optional parameters. See <see cref="InsertTextCommandOptions"/>.
    /// </param>
    /// <param name="cancellationToken">
    /// A token to cancel the asynchronous operation.
    /// </param>
    /// <returns>
    /// A task representing the asynchronous operation, containing a <see cref="InsertTextResult"/>.
    /// </returns>
    [global::System.Diagnostics.CodeAnalysis.Experimental("BIDICDP001")]
    public async Task<InsertTextResult> InsertTextAsync(string text, InsertTextCommandOptions? options = default, CancellationToken cancellationToken = default)
    {
        var @params = new InsertTextCommandParameters(Text: text);
        return await ExecuteCommandAsync(InsertTextCommand, @params, options, cancellationToken).ConfigureAwait(false);
    }
    private static readonly CdpCommand<InsertTextCommandParameters, InsertTextResult> InsertTextCommand = new("Input.insertText", JsonContext.InsertTextCommandParameters, JsonContext.InsertTextResult);

    /// <summary>
    /// This method sets the current candidate text for IME.
    /// Use imeCommitComposition to commit the final text.
    /// Use imeSetComposition with empty string as text to cancel composition.
    /// </summary>
    /// <remarks>
    /// Optional parameters (via <paramref name="options"/>):
    /// <list type="bullet">
    /// <item><description><b>ReplacementStart</b> - replacement start</description></item>
    /// <item><description><b>ReplacementEnd</b> - replacement end</description></item>
    /// </list>
    /// </remarks>
    /// <param name="text">
    /// The text to insert
    /// </param>
    /// <param name="selectionStart">
    /// selection start
    /// </param>
    /// <param name="selectionEnd">
    /// selection end
    /// </param>
    /// <param name="options">
    /// Optional parameters. See <see cref="ImeSetCompositionCommandOptions"/>.
    /// </param>
    /// <param name="cancellationToken">
    /// A token to cancel the asynchronous operation.
    /// </param>
    /// <returns>
    /// A task representing the asynchronous operation, containing a <see cref="ImeSetCompositionResult"/>.
    /// </returns>
    [global::System.Diagnostics.CodeAnalysis.Experimental("BIDICDP001")]
    public async Task<ImeSetCompositionResult> ImeSetCompositionAsync(string text, long selectionStart, long selectionEnd, ImeSetCompositionCommandOptions? options = default, CancellationToken cancellationToken = default)
    {
        var @params = new ImeSetCompositionCommandParameters(Text: text, SelectionStart: selectionStart, SelectionEnd: selectionEnd, ReplacementStart: options?.ReplacementStart, ReplacementEnd: options?.ReplacementEnd);
        return await ExecuteCommandAsync(ImeSetCompositionCommand, @params, options, cancellationToken).ConfigureAwait(false);
    }
    private static readonly CdpCommand<ImeSetCompositionCommandParameters, ImeSetCompositionResult> ImeSetCompositionCommand = new("Input.imeSetComposition", JsonContext.ImeSetCompositionCommandParameters, JsonContext.ImeSetCompositionResult);

    /// <summary>
    /// Dispatches a mouse event to the page.
    /// </summary>
    /// <remarks>
    /// Optional parameters (via <paramref name="options"/>):
    /// <list type="bullet">
    /// <item><description><b>Modifiers</b> - Bit field representing pressed modifier keys. Alt=1, Ctrl=2, Meta/Command=4, Shift=8 (default: 0).</description></item>
    /// <item><description><b>Timestamp</b> - Time at which the event occurred.</description></item>
    /// <item><description><b>Button</b> - Mouse button (default: "none").</description></item>
    /// <item><description><b>Buttons</b> - A number indicating which buttons are pressed on the mouse when a mouse event is triggered. Left=1, Right=2, Middle=4, Back=8, Forward=16, None=0.</description></item>
    /// <item><description><b>ClickCount</b> - Number of times the mouse button was clicked (default: 0).</description></item>
    /// <item><description><b>Force</b> - The normalized pressure, which has a range of [0,1] (default: 0).</description></item>
    /// <item><description><b>TangentialPressure</b> - The normalized tangential pressure, which has a range of [-1,1] (default: 0).</description></item>
    /// <item><description><b>TiltX</b> - The plane angle between the Y-Z plane and the plane containing both the stylus axis and the Y axis, in degrees of the range [-90,90], a positive tiltX is to the right (default: 0).</description></item>
    /// <item><description><b>TiltY</b> - The plane angle between the X-Z plane and the plane containing both the stylus axis and the X axis, in degrees of the range [-90,90], a positive tiltY is towards the user (default: 0).</description></item>
    /// <item><description><b>Twist</b> - The clockwise rotation of a pen stylus around its own major axis, in degrees in the range [0,359] (default: 0).</description></item>
    /// <item><description><b>DeltaX</b> - X delta in CSS pixels for mouse wheel event (default: 0).</description></item>
    /// <item><description><b>DeltaY</b> - Y delta in CSS pixels for mouse wheel event (default: 0).</description></item>
    /// <item><description><b>PointerType</b> - Pointer type (default: "mouse").</description></item>
    /// </list>
    /// </remarks>
    /// <param name="type">
    /// Type of the mouse event.
    /// </param>
    /// <param name="x">
    /// X coordinate of the event relative to the main frame's viewport in CSS pixels.
    /// </param>
    /// <param name="y">
    /// Y coordinate of the event relative to the main frame's viewport in CSS pixels. 0 refers to
    /// the top of the viewport and Y increases as it proceeds towards the bottom of the viewport.
    /// </param>
    /// <param name="options">
    /// Optional parameters. See <see cref="DispatchMouseEventCommandOptions"/>.
    /// </param>
    /// <param name="cancellationToken">
    /// A token to cancel the asynchronous operation.
    /// </param>
    /// <returns>
    /// A task representing the asynchronous operation, containing a <see cref="DispatchMouseEventResult"/>.
    /// </returns>
    public async Task<DispatchMouseEventResult> DispatchMouseEventAsync(string type, double x, double y, DispatchMouseEventCommandOptions? options = default, CancellationToken cancellationToken = default)
    {
        var @params = new DispatchMouseEventCommandParameters(Type: type, X: x, Y: y, Modifiers: options?.Modifiers, Timestamp: options?.Timestamp, Button: options?.Button, Buttons: options?.Buttons, ClickCount: options?.ClickCount, Force: options?.Force, TangentialPressure: options?.TangentialPressure, TiltX: options?.TiltX, TiltY: options?.TiltY, Twist: options?.Twist, DeltaX: options?.DeltaX, DeltaY: options?.DeltaY, PointerType: options?.PointerType);
        return await ExecuteCommandAsync(DispatchMouseEventCommand, @params, options, cancellationToken).ConfigureAwait(false);
    }
    private static readonly CdpCommand<DispatchMouseEventCommandParameters, DispatchMouseEventResult> DispatchMouseEventCommand = new("Input.dispatchMouseEvent", JsonContext.DispatchMouseEventCommandParameters, JsonContext.DispatchMouseEventResult);

    /// <summary>
    /// Dispatches a touch event to the page.
    /// </summary>
    /// <remarks>
    /// Optional parameters (via <paramref name="options"/>):
    /// <list type="bullet">
    /// <item><description><b>Modifiers</b> - Bit field representing pressed modifier keys. Alt=1, Ctrl=2, Meta/Command=4, Shift=8 (default: 0).</description></item>
    /// <item><description><b>Timestamp</b> - Time at which the event occurred.</description></item>
    /// </list>
    /// </remarks>
    /// <param name="type">
    /// Type of the touch event. TouchEnd and TouchCancel must not contain any touch points, while
    /// TouchStart and TouchMove must contains at least one.
    /// </param>
    /// <param name="touchPoints">
    /// Active touch points on the touch device. One event per any changed point (compared to
    /// previous touch event in a sequence) is generated, emulating pressing/moving/releasing points
    /// one by one.
    /// </param>
    /// <param name="options">
    /// Optional parameters. See <see cref="DispatchTouchEventCommandOptions"/>.
    /// </param>
    /// <param name="cancellationToken">
    /// A token to cancel the asynchronous operation.
    /// </param>
    /// <returns>
    /// A task representing the asynchronous operation, containing a <see cref="DispatchTouchEventResult"/>.
    /// </returns>
    public async Task<DispatchTouchEventResult> DispatchTouchEventAsync(string type, ImmutableArray<TouchPoint> touchPoints, DispatchTouchEventCommandOptions? options = default, CancellationToken cancellationToken = default)
    {
        var @params = new DispatchTouchEventCommandParameters(Type: type, TouchPoints: touchPoints, Modifiers: options?.Modifiers, Timestamp: options?.Timestamp);
        return await ExecuteCommandAsync(DispatchTouchEventCommand, @params, options, cancellationToken).ConfigureAwait(false);
    }
    private static readonly CdpCommand<DispatchTouchEventCommandParameters, DispatchTouchEventResult> DispatchTouchEventCommand = new("Input.dispatchTouchEvent", JsonContext.DispatchTouchEventCommandParameters, JsonContext.DispatchTouchEventResult);

    /// <summary>
    /// Cancels any active dragging in the page.
    /// </summary>
    /// <param name="options">
    /// Optional parameters. See <see cref="CancelDraggingCommandOptions"/>.
    /// </param>
    /// <param name="cancellationToken">
    /// A token to cancel the asynchronous operation.
    /// </param>
    /// <returns>
    /// A task representing the asynchronous operation, containing a <see cref="CancelDraggingResult"/>.
    /// </returns>
    public async Task<CancelDraggingResult> CancelDraggingAsync(CancelDraggingCommandOptions? options = default, CancellationToken cancellationToken = default)
    {
        var @params = new CancelDraggingCommandParameters();
        return await ExecuteCommandAsync(CancelDraggingCommand, @params, options, cancellationToken).ConfigureAwait(false);
    }
    private static readonly CdpCommand<CancelDraggingCommandParameters, CancelDraggingResult> CancelDraggingCommand = new("Input.cancelDragging", JsonContext.CancelDraggingCommandParameters, JsonContext.CancelDraggingResult);

    /// <summary>
    /// Emulates touch event from the mouse event parameters.
    /// </summary>
    /// <remarks>
    /// Optional parameters (via <paramref name="options"/>):
    /// <list type="bullet">
    /// <item><description><b>Timestamp</b> - Time at which the event occurred (default: current time).</description></item>
    /// <item><description><b>DeltaX</b> - X delta in DIP for mouse wheel event (default: 0).</description></item>
    /// <item><description><b>DeltaY</b> - Y delta in DIP for mouse wheel event (default: 0).</description></item>
    /// <item><description><b>Modifiers</b> - Bit field representing pressed modifier keys. Alt=1, Ctrl=2, Meta/Command=4, Shift=8 (default: 0).</description></item>
    /// <item><description><b>ClickCount</b> - Number of times the mouse button was clicked (default: 0).</description></item>
    /// </list>
    /// </remarks>
    /// <param name="type">
    /// Type of the mouse event.
    /// </param>
    /// <param name="x">
    /// X coordinate of the mouse pointer in DIP.
    /// </param>
    /// <param name="y">
    /// Y coordinate of the mouse pointer in DIP.
    /// </param>
    /// <param name="button">
    /// Mouse button. Only "none", "left", "right" are supported.
    /// </param>
    /// <param name="options">
    /// Optional parameters. See <see cref="EmulateTouchFromMouseEventCommandOptions"/>.
    /// </param>
    /// <param name="cancellationToken">
    /// A token to cancel the asynchronous operation.
    /// </param>
    /// <returns>
    /// A task representing the asynchronous operation, containing a <see cref="EmulateTouchFromMouseEventResult"/>.
    /// </returns>
    [global::System.Diagnostics.CodeAnalysis.Experimental("BIDICDP001")]
    public async Task<EmulateTouchFromMouseEventResult> EmulateTouchFromMouseEventAsync(string type, long x, long y, MouseButton button, EmulateTouchFromMouseEventCommandOptions? options = default, CancellationToken cancellationToken = default)
    {
        var @params = new EmulateTouchFromMouseEventCommandParameters(Type: type, X: x, Y: y, Button: button, Timestamp: options?.Timestamp, DeltaX: options?.DeltaX, DeltaY: options?.DeltaY, Modifiers: options?.Modifiers, ClickCount: options?.ClickCount);
        return await ExecuteCommandAsync(EmulateTouchFromMouseEventCommand, @params, options, cancellationToken).ConfigureAwait(false);
    }
    private static readonly CdpCommand<EmulateTouchFromMouseEventCommandParameters, EmulateTouchFromMouseEventResult> EmulateTouchFromMouseEventCommand = new("Input.emulateTouchFromMouseEvent", JsonContext.EmulateTouchFromMouseEventCommandParameters, JsonContext.EmulateTouchFromMouseEventResult);

    /// <summary>
    /// Ignores input events (useful while auditing page).
    /// </summary>
    /// <param name="ignore">
    /// Ignores input events processing when set to true.
    /// </param>
    /// <param name="options">
    /// Optional parameters. See <see cref="SetIgnoreInputEventsCommandOptions"/>.
    /// </param>
    /// <param name="cancellationToken">
    /// A token to cancel the asynchronous operation.
    /// </param>
    /// <returns>
    /// A task representing the asynchronous operation, containing a <see cref="SetIgnoreInputEventsResult"/>.
    /// </returns>
    public async Task<SetIgnoreInputEventsResult> SetIgnoreInputEventsAsync(bool ignore, SetIgnoreInputEventsCommandOptions? options = default, CancellationToken cancellationToken = default)
    {
        var @params = new SetIgnoreInputEventsCommandParameters(Ignore: ignore);
        return await ExecuteCommandAsync(SetIgnoreInputEventsCommand, @params, options, cancellationToken).ConfigureAwait(false);
    }
    private static readonly CdpCommand<SetIgnoreInputEventsCommandParameters, SetIgnoreInputEventsResult> SetIgnoreInputEventsCommand = new("Input.setIgnoreInputEvents", JsonContext.SetIgnoreInputEventsCommandParameters, JsonContext.SetIgnoreInputEventsResult);

    /// <summary>
    /// Prevents default drag and drop behavior and instead emits <b>Input.dragIntercepted</b> events.
    /// Drag and drop behavior can be directly controlled via <b>Input.dispatchDragEvent</b>.
    /// </summary>
    /// <param name="enabled">
    /// </param>
    /// <param name="options">
    /// Optional parameters. See <see cref="SetInterceptDragsCommandOptions"/>.
    /// </param>
    /// <param name="cancellationToken">
    /// A token to cancel the asynchronous operation.
    /// </param>
    /// <returns>
    /// A task representing the asynchronous operation, containing a <see cref="SetInterceptDragsResult"/>.
    /// </returns>
    [global::System.Diagnostics.CodeAnalysis.Experimental("BIDICDP001")]
    public async Task<SetInterceptDragsResult> SetInterceptDragsAsync(bool enabled, SetInterceptDragsCommandOptions? options = default, CancellationToken cancellationToken = default)
    {
        var @params = new SetInterceptDragsCommandParameters(Enabled: enabled);
        return await ExecuteCommandAsync(SetInterceptDragsCommand, @params, options, cancellationToken).ConfigureAwait(false);
    }
    private static readonly CdpCommand<SetInterceptDragsCommandParameters, SetInterceptDragsResult> SetInterceptDragsCommand = new("Input.setInterceptDrags", JsonContext.SetInterceptDragsCommandParameters, JsonContext.SetInterceptDragsResult);

    /// <summary>
    /// Synthesizes a pinch gesture over a time period by issuing appropriate touch events.
    /// </summary>
    /// <remarks>
    /// Optional parameters (via <paramref name="options"/>):
    /// <list type="bullet">
    /// <item><description><b>RelativeSpeed</b> - Relative pointer speed in pixels per second (default: 800).</description></item>
    /// <item><description><b>GestureSourceType</b> - Which type of input events to be generated (default: 'default', which queries the platform for the preferred input type).</description></item>
    /// </list>
    /// </remarks>
    /// <param name="x">
    /// X coordinate of the start of the gesture in CSS pixels.
    /// </param>
    /// <param name="y">
    /// Y coordinate of the start of the gesture in CSS pixels.
    /// </param>
    /// <param name="scaleFactor">
    /// Relative scale factor after zooming (&gt;1.0 zooms in, &lt;1.0 zooms out).
    /// </param>
    /// <param name="options">
    /// Optional parameters. See <see cref="SynthesizePinchGestureCommandOptions"/>.
    /// </param>
    /// <param name="cancellationToken">
    /// A token to cancel the asynchronous operation.
    /// </param>
    /// <returns>
    /// A task representing the asynchronous operation, containing a <see cref="SynthesizePinchGestureResult"/>.
    /// </returns>
    [global::System.Diagnostics.CodeAnalysis.Experimental("BIDICDP001")]
    public async Task<SynthesizePinchGestureResult> SynthesizePinchGestureAsync(double x, double y, double scaleFactor, SynthesizePinchGestureCommandOptions? options = default, CancellationToken cancellationToken = default)
    {
        var @params = new SynthesizePinchGestureCommandParameters(X: x, Y: y, ScaleFactor: scaleFactor, RelativeSpeed: options?.RelativeSpeed, GestureSourceType: options?.GestureSourceType);
        return await ExecuteCommandAsync(SynthesizePinchGestureCommand, @params, options, cancellationToken).ConfigureAwait(false);
    }
    private static readonly CdpCommand<SynthesizePinchGestureCommandParameters, SynthesizePinchGestureResult> SynthesizePinchGestureCommand = new("Input.synthesizePinchGesture", JsonContext.SynthesizePinchGestureCommandParameters, JsonContext.SynthesizePinchGestureResult);

    /// <summary>
    /// Synthesizes a scroll gesture over a time period by issuing appropriate touch events.
    /// </summary>
    /// <remarks>
    /// Optional parameters (via <paramref name="options"/>):
    /// <list type="bullet">
    /// <item><description><b>XDistance</b> - The distance to scroll along the X axis (positive to scroll left).</description></item>
    /// <item><description><b>YDistance</b> - The distance to scroll along the Y axis (positive to scroll up).</description></item>
    /// <item><description><b>XOverscroll</b> - The number of additional pixels to scroll back along the X axis, in addition to the given distance.</description></item>
    /// <item><description><b>YOverscroll</b> - The number of additional pixels to scroll back along the Y axis, in addition to the given distance.</description></item>
    /// <item><description><b>PreventFling</b> - Prevent fling (default: true).</description></item>
    /// <item><description><b>Speed</b> - Swipe speed in pixels per second (default: 800).</description></item>
    /// <item><description><b>GestureSourceType</b> - Which type of input events to be generated (default: 'default', which queries the platform for the preferred input type).</description></item>
    /// <item><description><b>RepeatCount</b> - The number of times to repeat the gesture (default: 0).</description></item>
    /// <item><description><b>RepeatDelayMs</b> - The number of milliseconds delay between each repeat. (default: 250).</description></item>
    /// <item><description><b>InteractionMarkerName</b> - The name of the interaction markers to generate, if not empty (default: "").</description></item>
    /// </list>
    /// </remarks>
    /// <param name="x">
    /// X coordinate of the start of the gesture in CSS pixels.
    /// </param>
    /// <param name="y">
    /// Y coordinate of the start of the gesture in CSS pixels.
    /// </param>
    /// <param name="options">
    /// Optional parameters. See <see cref="SynthesizeScrollGestureCommandOptions"/>.
    /// </param>
    /// <param name="cancellationToken">
    /// A token to cancel the asynchronous operation.
    /// </param>
    /// <returns>
    /// A task representing the asynchronous operation, containing a <see cref="SynthesizeScrollGestureResult"/>.
    /// </returns>
    [global::System.Diagnostics.CodeAnalysis.Experimental("BIDICDP001")]
    public async Task<SynthesizeScrollGestureResult> SynthesizeScrollGestureAsync(double x, double y, SynthesizeScrollGestureCommandOptions? options = default, CancellationToken cancellationToken = default)
    {
        var @params = new SynthesizeScrollGestureCommandParameters(X: x, Y: y, XDistance: options?.XDistance, YDistance: options?.YDistance, XOverscroll: options?.XOverscroll, YOverscroll: options?.YOverscroll, PreventFling: options?.PreventFling, Speed: options?.Speed, GestureSourceType: options?.GestureSourceType, RepeatCount: options?.RepeatCount, RepeatDelayMs: options?.RepeatDelayMs, InteractionMarkerName: options?.InteractionMarkerName);
        return await ExecuteCommandAsync(SynthesizeScrollGestureCommand, @params, options, cancellationToken).ConfigureAwait(false);
    }
    private static readonly CdpCommand<SynthesizeScrollGestureCommandParameters, SynthesizeScrollGestureResult> SynthesizeScrollGestureCommand = new("Input.synthesizeScrollGesture", JsonContext.SynthesizeScrollGestureCommandParameters, JsonContext.SynthesizeScrollGestureResult);

    /// <summary>
    /// Synthesizes a tap gesture over a time period by issuing appropriate touch events.
    /// </summary>
    /// <remarks>
    /// Optional parameters (via <paramref name="options"/>):
    /// <list type="bullet">
    /// <item><description><b>Duration</b> - Duration between touchdown and touchup events in ms (default: 50).</description></item>
    /// <item><description><b>TapCount</b> - Number of times to perform the tap (e.g. 2 for double tap, default: 1).</description></item>
    /// <item><description><b>GestureSourceType</b> - Which type of input events to be generated (default: 'default', which queries the platform for the preferred input type).</description></item>
    /// </list>
    /// </remarks>
    /// <param name="x">
    /// X coordinate of the start of the gesture in CSS pixels.
    /// </param>
    /// <param name="y">
    /// Y coordinate of the start of the gesture in CSS pixels.
    /// </param>
    /// <param name="options">
    /// Optional parameters. See <see cref="SynthesizeTapGestureCommandOptions"/>.
    /// </param>
    /// <param name="cancellationToken">
    /// A token to cancel the asynchronous operation.
    /// </param>
    /// <returns>
    /// A task representing the asynchronous operation, containing a <see cref="SynthesizeTapGestureResult"/>.
    /// </returns>
    [global::System.Diagnostics.CodeAnalysis.Experimental("BIDICDP001")]
    public async Task<SynthesizeTapGestureResult> SynthesizeTapGestureAsync(double x, double y, SynthesizeTapGestureCommandOptions? options = default, CancellationToken cancellationToken = default)
    {
        var @params = new SynthesizeTapGestureCommandParameters(X: x, Y: y, Duration: options?.Duration, TapCount: options?.TapCount, GestureSourceType: options?.GestureSourceType);
        return await ExecuteCommandAsync(SynthesizeTapGestureCommand, @params, options, cancellationToken).ConfigureAwait(false);
    }
    private static readonly CdpCommand<SynthesizeTapGestureCommandParameters, SynthesizeTapGestureResult> SynthesizeTapGestureCommand = new("Input.synthesizeTapGesture", JsonContext.SynthesizeTapGestureCommandParameters, JsonContext.SynthesizeTapGestureResult);

    /// <summary>
    /// Emitted only when <b>Input.setInterceptDrags</b> is enabled. Use this data with <b>Input.dispatchDragEvent</b> to
    /// restore normal drag and drop behavior.
    /// </summary>
    /// <remarks>
    /// Event args (<see cref="DragInterceptedEventArgs"/>):
    /// <list type="bullet">
    /// <item><description><b>Data</b></description></item>
    /// </list>
    /// </remarks>
    [global::System.Diagnostics.CodeAnalysis.Experimental("BIDICDP001")]
    public IEventSource<DragInterceptedEventArgs> DragIntercepted => CreateCdpEventSource(InputDomainEvent.DragIntercepted);
}

internal sealed record DispatchDragEventCommandParameters(string Type, double X, double Y, DragData Data, long? Modifiers) : Parameters;

/// <summary>
/// Optional parameters for <see cref="InputDomain.DispatchDragEventAsync"/>.
/// </summary>
public sealed record DispatchDragEventCommandOptions : CdpCommandOptions
{
    /// <summary>
    /// Bit field representing pressed modifier keys. Alt=1, Ctrl=2, Meta/Command=4, Shift=8
    /// (default: 0).
    /// </summary>
    public long? Modifiers { get; init; }
}

/// <summary>
/// </summary>
public sealed record DispatchDragEventResult() : EmptyResult;


internal sealed record DispatchKeyEventCommandParameters(string Type, long? Modifiers, TimeSinceEpoch? Timestamp, string? Text, string? UnmodifiedText, string? KeyIdentifier, string? Code, string? Key, long? WindowsVirtualKeyCode, long? NativeVirtualKeyCode, bool? AutoRepeat, bool? IsKeypad, bool? IsSystemKey, long? Location, ImmutableArray<string>? Commands) : Parameters;

/// <summary>
/// Optional parameters for <see cref="InputDomain.DispatchKeyEventAsync"/>.
/// </summary>
public sealed record DispatchKeyEventCommandOptions : CdpCommandOptions
{
    /// <summary>
    /// Bit field representing pressed modifier keys. Alt=1, Ctrl=2, Meta/Command=4, Shift=8
    /// (default: 0).
    /// </summary>
    public long? Modifiers { get; init; }

    /// <summary>
    /// Time at which the event occurred.
    /// </summary>
    public TimeSinceEpoch? Timestamp { get; init; }

    /// <summary>
    /// Text as generated by processing a virtual key code with a keyboard layout. Not needed for
    /// for <b>keyUp</b> and <b>rawKeyDown</b> events (default: "")
    /// </summary>
    public string? Text { get; init; }

    /// <summary>
    /// Text that would have been generated by the keyboard if no modifiers were pressed (except for
    /// shift). Useful for shortcut (accelerator) key handling (default: "").
    /// </summary>
    public string? UnmodifiedText { get; init; }

    /// <summary>
    /// Unique key identifier (e.g., 'U+0041') (default: "").
    /// </summary>
    public string? KeyIdentifier { get; init; }

    /// <summary>
    /// Unique DOM defined string value for each physical key (e.g., 'KeyA') (default: "").
    /// </summary>
    public string? Code { get; init; }

    /// <summary>
    /// Unique DOM defined string value describing the meaning of the key in the context of active
    /// modifiers, keyboard layout, etc (e.g., 'AltGr') (default: "").
    /// </summary>
    public string? Key { get; init; }

    /// <summary>
    /// Windows virtual key code (default: 0).
    /// </summary>
    public long? WindowsVirtualKeyCode { get; init; }

    /// <summary>
    /// Native virtual key code (default: 0).
    /// </summary>
    public long? NativeVirtualKeyCode { get; init; }

    /// <summary>
    /// Whether the event was generated from auto repeat (default: false).
    /// </summary>
    public bool? AutoRepeat { get; init; }

    /// <summary>
    /// Whether the event was generated from the keypad (default: false).
    /// </summary>
    public bool? IsKeypad { get; init; }

    /// <summary>
    /// Whether the event was a system key event (default: false).
    /// </summary>
    public bool? IsSystemKey { get; init; }

    /// <summary>
    /// Whether the event was from the left or right side of the keyboard. 1=Left, 2=Right (default:
    /// 0).
    /// </summary>
    public long? Location { get; init; }

    /// <summary>
    /// Editing commands to send with the key event (e.g., 'selectAll') (default: []).
    /// These are related to but not equal the command names used in <b>document.execCommand</b> and NSStandardKeyBindingResponding.
    /// See https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/editing/commands/editor_command_names.h for valid command names.
    /// </summary>
    public ImmutableArray<string>? Commands { get; init; }
}

/// <summary>
/// </summary>
public sealed record DispatchKeyEventResult() : EmptyResult;


internal sealed record InsertTextCommandParameters(string Text) : Parameters;

/// <summary>
/// Optional parameters for <see cref="InputDomain.InsertTextAsync"/>.
/// </summary>
public sealed record InsertTextCommandOptions : CdpCommandOptions
{
}

/// <summary>
/// </summary>
public sealed record InsertTextResult() : EmptyResult;


internal sealed record ImeSetCompositionCommandParameters(string Text, long SelectionStart, long SelectionEnd, long? ReplacementStart, long? ReplacementEnd) : Parameters;

/// <summary>
/// Optional parameters for <see cref="InputDomain.ImeSetCompositionAsync"/>.
/// </summary>
public sealed record ImeSetCompositionCommandOptions : CdpCommandOptions
{
    /// <summary>
    /// replacement start
    /// </summary>
    public long? ReplacementStart { get; init; }

    /// <summary>
    /// replacement end
    /// </summary>
    public long? ReplacementEnd { get; init; }
}

/// <summary>
/// </summary>
public sealed record ImeSetCompositionResult() : EmptyResult;


internal sealed record DispatchMouseEventCommandParameters(string Type, double X, double Y, long? Modifiers, TimeSinceEpoch? Timestamp, MouseButton? Button, long? Buttons, long? ClickCount, double? Force, double? TangentialPressure, double? TiltX, double? TiltY, long? Twist, double? DeltaX, double? DeltaY, string? PointerType) : Parameters;

/// <summary>
/// Optional parameters for <see cref="InputDomain.DispatchMouseEventAsync"/>.
/// </summary>
public sealed record DispatchMouseEventCommandOptions : CdpCommandOptions
{
    /// <summary>
    /// Bit field representing pressed modifier keys. Alt=1, Ctrl=2, Meta/Command=4, Shift=8
    /// (default: 0).
    /// </summary>
    public long? Modifiers { get; init; }

    /// <summary>
    /// Time at which the event occurred.
    /// </summary>
    public TimeSinceEpoch? Timestamp { get; init; }

    /// <summary>
    /// Mouse button (default: "none").
    /// </summary>
    public MouseButton? Button { get; init; }

    /// <summary>
    /// A number indicating which buttons are pressed on the mouse when a mouse event is triggered.
    /// Left=1, Right=2, Middle=4, Back=8, Forward=16, None=0.
    /// </summary>
    public long? Buttons { get; init; }

    /// <summary>
    /// Number of times the mouse button was clicked (default: 0).
    /// </summary>
    public long? ClickCount { get; init; }

    /// <summary>
    /// The normalized pressure, which has a range of [0,1] (default: 0).
    /// </summary>
    public double? Force { get; init; }

    /// <summary>
    /// The normalized tangential pressure, which has a range of [-1,1] (default: 0).
    /// </summary>
    public double? TangentialPressure { get; init; }

    /// <summary>
    /// The plane angle between the Y-Z plane and the plane containing both the stylus axis and the Y axis, in degrees of the range [-90,90], a positive tiltX is to the right (default: 0).
    /// </summary>
    public double? TiltX { get; init; }

    /// <summary>
    /// The plane angle between the X-Z plane and the plane containing both the stylus axis and the X axis, in degrees of the range [-90,90], a positive tiltY is towards the user (default: 0).
    /// </summary>
    public double? TiltY { get; init; }

    /// <summary>
    /// The clockwise rotation of a pen stylus around its own major axis, in degrees in the range [0,359] (default: 0).
    /// </summary>
    public long? Twist { get; init; }

    /// <summary>
    /// X delta in CSS pixels for mouse wheel event (default: 0).
    /// </summary>
    public double? DeltaX { get; init; }

    /// <summary>
    /// Y delta in CSS pixels for mouse wheel event (default: 0).
    /// </summary>
    public double? DeltaY { get; init; }

    /// <summary>
    /// Pointer type (default: "mouse").
    /// </summary>
    public string? PointerType { get; init; }
}

/// <summary>
/// </summary>
public sealed record DispatchMouseEventResult() : EmptyResult;


internal sealed record DispatchTouchEventCommandParameters(string Type, ImmutableArray<TouchPoint> TouchPoints, long? Modifiers, TimeSinceEpoch? Timestamp) : Parameters;

/// <summary>
/// Optional parameters for <see cref="InputDomain.DispatchTouchEventAsync"/>.
/// </summary>
public sealed record DispatchTouchEventCommandOptions : CdpCommandOptions
{
    /// <summary>
    /// Bit field representing pressed modifier keys. Alt=1, Ctrl=2, Meta/Command=4, Shift=8
    /// (default: 0).
    /// </summary>
    public long? Modifiers { get; init; }

    /// <summary>
    /// Time at which the event occurred.
    /// </summary>
    public TimeSinceEpoch? Timestamp { get; init; }
}

/// <summary>
/// </summary>
public sealed record DispatchTouchEventResult() : EmptyResult;


internal sealed record CancelDraggingCommandParameters() : Parameters;

/// <summary>
/// Optional parameters for <see cref="InputDomain.CancelDraggingAsync"/>.
/// </summary>
public sealed record CancelDraggingCommandOptions : CdpCommandOptions
{
}

/// <summary>
/// </summary>
public sealed record CancelDraggingResult() : EmptyResult;


internal sealed record EmulateTouchFromMouseEventCommandParameters(string Type, long X, long Y, MouseButton Button, TimeSinceEpoch? Timestamp, double? DeltaX, double? DeltaY, long? Modifiers, long? ClickCount) : Parameters;

/// <summary>
/// Optional parameters for <see cref="InputDomain.EmulateTouchFromMouseEventAsync"/>.
/// </summary>
public sealed record EmulateTouchFromMouseEventCommandOptions : CdpCommandOptions
{
    /// <summary>
    /// Time at which the event occurred (default: current time).
    /// </summary>
    public TimeSinceEpoch? Timestamp { get; init; }

    /// <summary>
    /// X delta in DIP for mouse wheel event (default: 0).
    /// </summary>
    public double? DeltaX { get; init; }

    /// <summary>
    /// Y delta in DIP for mouse wheel event (default: 0).
    /// </summary>
    public double? DeltaY { get; init; }

    /// <summary>
    /// Bit field representing pressed modifier keys. Alt=1, Ctrl=2, Meta/Command=4, Shift=8
    /// (default: 0).
    /// </summary>
    public long? Modifiers { get; init; }

    /// <summary>
    /// Number of times the mouse button was clicked (default: 0).
    /// </summary>
    public long? ClickCount { get; init; }
}

/// <summary>
/// </summary>
public sealed record EmulateTouchFromMouseEventResult() : EmptyResult;


internal sealed record SetIgnoreInputEventsCommandParameters(bool Ignore) : Parameters;

/// <summary>
/// Optional parameters for <see cref="InputDomain.SetIgnoreInputEventsAsync"/>.
/// </summary>
public sealed record SetIgnoreInputEventsCommandOptions : CdpCommandOptions
{
}

/// <summary>
/// </summary>
public sealed record SetIgnoreInputEventsResult() : EmptyResult;


internal sealed record SetInterceptDragsCommandParameters(bool Enabled) : Parameters;

/// <summary>
/// Optional parameters for <see cref="InputDomain.SetInterceptDragsAsync"/>.
/// </summary>
public sealed record SetInterceptDragsCommandOptions : CdpCommandOptions
{
}

/// <summary>
/// </summary>
public sealed record SetInterceptDragsResult() : EmptyResult;


internal sealed record SynthesizePinchGestureCommandParameters(double X, double Y, double ScaleFactor, long? RelativeSpeed, GestureSourceType? GestureSourceType) : Parameters;

/// <summary>
/// Optional parameters for <see cref="InputDomain.SynthesizePinchGestureAsync"/>.
/// </summary>
public sealed record SynthesizePinchGestureCommandOptions : CdpCommandOptions
{
    /// <summary>
    /// Relative pointer speed in pixels per second (default: 800).
    /// </summary>
    public long? RelativeSpeed { get; init; }

    /// <summary>
    /// Which type of input events to be generated (default: 'default', which queries the platform
    /// for the preferred input type).
    /// </summary>
    public GestureSourceType? GestureSourceType { get; init; }
}

/// <summary>
/// </summary>
public sealed record SynthesizePinchGestureResult() : EmptyResult;


internal sealed record SynthesizeScrollGestureCommandParameters(double X, double Y, double? XDistance, double? YDistance, double? XOverscroll, double? YOverscroll, bool? PreventFling, long? Speed, GestureSourceType? GestureSourceType, long? RepeatCount, long? RepeatDelayMs, string? InteractionMarkerName) : Parameters;

/// <summary>
/// Optional parameters for <see cref="InputDomain.SynthesizeScrollGestureAsync"/>.
/// </summary>
public sealed record SynthesizeScrollGestureCommandOptions : CdpCommandOptions
{
    /// <summary>
    /// The distance to scroll along the X axis (positive to scroll left).
    /// </summary>
    public double? XDistance { get; init; }

    /// <summary>
    /// The distance to scroll along the Y axis (positive to scroll up).
    /// </summary>
    public double? YDistance { get; init; }

    /// <summary>
    /// The number of additional pixels to scroll back along the X axis, in addition to the given
    /// distance.
    /// </summary>
    public double? XOverscroll { get; init; }

    /// <summary>
    /// The number of additional pixels to scroll back along the Y axis, in addition to the given
    /// distance.
    /// </summary>
    public double? YOverscroll { get; init; }

    /// <summary>
    /// Prevent fling (default: true).
    /// </summary>
    public bool? PreventFling { get; init; }

    /// <summary>
    /// Swipe speed in pixels per second (default: 800).
    /// </summary>
    public long? Speed { get; init; }

    /// <summary>
    /// Which type of input events to be generated (default: 'default', which queries the platform
    /// for the preferred input type).
    /// </summary>
    public GestureSourceType? GestureSourceType { get; init; }

    /// <summary>
    /// The number of times to repeat the gesture (default: 0).
    /// </summary>
    public long? RepeatCount { get; init; }

    /// <summary>
    /// The number of milliseconds delay between each repeat. (default: 250).
    /// </summary>
    public long? RepeatDelayMs { get; init; }

    /// <summary>
    /// The name of the interaction markers to generate, if not empty (default: "").
    /// </summary>
    public string? InteractionMarkerName { get; init; }
}

/// <summary>
/// </summary>
public sealed record SynthesizeScrollGestureResult() : EmptyResult;


internal sealed record SynthesizeTapGestureCommandParameters(double X, double Y, long? Duration, long? TapCount, GestureSourceType? GestureSourceType) : Parameters;

/// <summary>
/// Optional parameters for <see cref="InputDomain.SynthesizeTapGestureAsync"/>.
/// </summary>
public sealed record SynthesizeTapGestureCommandOptions : CdpCommandOptions
{
    /// <summary>
    /// Duration between touchdown and touchup events in ms (default: 50).
    /// </summary>
    public long? Duration { get; init; }

    /// <summary>
    /// Number of times to perform the tap (e.g. 2 for double tap, default: 1).
    /// </summary>
    public long? TapCount { get; init; }

    /// <summary>
    /// Which type of input events to be generated (default: 'default', which queries the platform
    /// for the preferred input type).
    /// </summary>
    public GestureSourceType? GestureSourceType { get; init; }
}

/// <summary>
/// </summary>
public sealed record SynthesizeTapGestureResult() : EmptyResult;


/// <summary>
/// Emitted only when <b>Input.setInterceptDrags</b> is enabled. Use this data with <b>Input.dispatchDragEvent</b> to
/// restore normal drag and drop behavior.
/// </summary>
/// <param name="Data">
/// </param>
public sealed record DragInterceptedEventArgs(DragData Data) : OpenQA.Selenium.BiDi.EventArgs;

/// <summary>
/// </summary>
/// <param name="X">
/// X coordinate of the event relative to the main frame's viewport in CSS pixels.
/// </param>
/// <param name="Y">
/// Y coordinate of the event relative to the main frame's viewport in CSS pixels. 0 refers to
/// the top of the viewport and Y increases as it proceeds towards the bottom of the viewport.
/// </param>
public sealed record TouchPoint(double X, double Y)
{
    /// <summary>
    /// X radius of the touch area (default: 1.0).
    /// </summary>
    public double? RadiusX { get; init; }

    /// <summary>
    /// Y radius of the touch area (default: 1.0).
    /// </summary>
    public double? RadiusY { get; init; }

    /// <summary>
    /// Rotation angle (default: 0.0).
    /// </summary>
    public double? RotationAngle { get; init; }

    /// <summary>
    /// Force (default: 1.0).
    /// </summary>
    public double? Force { get; init; }

    /// <summary>
    /// The normalized tangential pressure, which has a range of [-1,1] (default: 0).
    /// </summary>
    public double? TangentialPressure { get; init; }

    /// <summary>
    /// The plane angle between the Y-Z plane and the plane containing both the stylus axis and the Y axis, in degrees of the range [-90,90], a positive tiltX is to the right (default: 0)
    /// </summary>
    public double? TiltX { get; init; }

    /// <summary>
    /// The plane angle between the X-Z plane and the plane containing both the stylus axis and the X axis, in degrees of the range [-90,90], a positive tiltY is towards the user (default: 0).
    /// </summary>
    public double? TiltY { get; init; }

    /// <summary>
    /// The clockwise rotation of a pen stylus around its own major axis, in degrees in the range [0,359] (default: 0).
    /// </summary>
    public long? Twist { get; init; }

    /// <summary>
    /// Identifier used to track touch sources between events, must be unique within an event.
    /// </summary>
    public double? Id { get; init; }
}

/// <summary>
/// </summary>
[global::System.Text.Json.Serialization.JsonConverter(typeof(Json.JsonStringEnumConverter<GestureSourceType>))]
public enum GestureSourceType
{
    /// <summary>
    /// </summary>
    [global::System.Text.Json.Serialization.JsonStringEnumMemberName("default")]
    Default,
    /// <summary>
    /// </summary>
    [global::System.Text.Json.Serialization.JsonStringEnumMemberName("touch")]
    Touch,
    /// <summary>
    /// </summary>
    [global::System.Text.Json.Serialization.JsonStringEnumMemberName("mouse")]
    Mouse,
}

/// <summary>
/// </summary>
[global::System.Text.Json.Serialization.JsonConverter(typeof(Json.JsonStringEnumConverter<MouseButton>))]
public enum MouseButton
{
    /// <summary>
    /// </summary>
    [global::System.Text.Json.Serialization.JsonStringEnumMemberName("none")]
    None,
    /// <summary>
    /// </summary>
    [global::System.Text.Json.Serialization.JsonStringEnumMemberName("left")]
    Left,
    /// <summary>
    /// </summary>
    [global::System.Text.Json.Serialization.JsonStringEnumMemberName("middle")]
    Middle,
    /// <summary>
    /// </summary>
    [global::System.Text.Json.Serialization.JsonStringEnumMemberName("right")]
    Right,
    /// <summary>
    /// </summary>
    [global::System.Text.Json.Serialization.JsonStringEnumMemberName("back")]
    Back,
    /// <summary>
    /// </summary>
    [global::System.Text.Json.Serialization.JsonStringEnumMemberName("forward")]
    Forward,
}

/// <summary>
/// UTC time in seconds, counted from January 1, 1970.
/// </summary>
[global::System.Text.Json.Serialization.JsonConverter(typeof(Json.NumberRemoteIdConverter<TimeSinceEpoch>))]
public record TimeSinceEpoch : INumberRemoteId
{
    double INumberRemoteId.Id { get; init; }
}

/// <summary>
/// </summary>
/// <param name="MimeType">
/// Mime type of the dragged data.
/// </param>
/// <param name="Data">
/// Depending of the value of <b>mimeType</b>, it contains the dragged link,
/// text, HTML markup or any other data.
/// </param>
public sealed record DragDataItem(string MimeType, string Data)
{
    /// <summary>
    /// Title associated with a link. Only valid when <b>mimeType</b> == "text/uri-list".
    /// </summary>
    public string? Title { get; init; }

    /// <summary>
    /// Stores the base URL for the contained markup. Only valid when <b>mimeType</b>
    /// == "text/html".
    /// </summary>
    public string? BaseURL { get; init; }
}

/// <summary>
/// </summary>
/// <param name="Items">
/// </param>
/// <param name="DragOperationsMask">
/// Bit field representing allowed drag operations. Copy = 1, Link = 2, Move = 16
/// </param>
public sealed record DragData(IReadOnlyList<DragDataItem> Items, long DragOperationsMask)
{
    /// <summary>
    /// List of filenames that should be included when dropping
    /// </summary>
    public IReadOnlyList<string>? Files { get; init; }
}

[JsonSerializable(typeof(DispatchDragEventCommandParameters), TypeInfoPropertyName = "DispatchDragEventCommandParameters")]
[JsonSerializable(typeof(DispatchDragEventResult), TypeInfoPropertyName = "DispatchDragEventResult")]
[JsonSerializable(typeof(DispatchKeyEventCommandParameters), TypeInfoPropertyName = "DispatchKeyEventCommandParameters")]
[JsonSerializable(typeof(DispatchKeyEventResult), TypeInfoPropertyName = "DispatchKeyEventResult")]
[JsonSerializable(typeof(InsertTextCommandParameters), TypeInfoPropertyName = "InsertTextCommandParameters")]
[JsonSerializable(typeof(InsertTextResult), TypeInfoPropertyName = "InsertTextResult")]
[JsonSerializable(typeof(ImeSetCompositionCommandParameters), TypeInfoPropertyName = "ImeSetCompositionCommandParameters")]
[JsonSerializable(typeof(ImeSetCompositionResult), TypeInfoPropertyName = "ImeSetCompositionResult")]
[JsonSerializable(typeof(DispatchMouseEventCommandParameters), TypeInfoPropertyName = "DispatchMouseEventCommandParameters")]
[JsonSerializable(typeof(DispatchMouseEventResult), TypeInfoPropertyName = "DispatchMouseEventResult")]
[JsonSerializable(typeof(DispatchTouchEventCommandParameters), TypeInfoPropertyName = "DispatchTouchEventCommandParameters")]
[JsonSerializable(typeof(DispatchTouchEventResult), TypeInfoPropertyName = "DispatchTouchEventResult")]
[JsonSerializable(typeof(CancelDraggingCommandParameters), TypeInfoPropertyName = "CancelDraggingCommandParameters")]
[JsonSerializable(typeof(CancelDraggingResult), TypeInfoPropertyName = "CancelDraggingResult")]
[JsonSerializable(typeof(EmulateTouchFromMouseEventCommandParameters), TypeInfoPropertyName = "EmulateTouchFromMouseEventCommandParameters")]
[JsonSerializable(typeof(EmulateTouchFromMouseEventResult), TypeInfoPropertyName = "EmulateTouchFromMouseEventResult")]
[JsonSerializable(typeof(SetIgnoreInputEventsCommandParameters), TypeInfoPropertyName = "SetIgnoreInputEventsCommandParameters")]
[JsonSerializable(typeof(SetIgnoreInputEventsResult), TypeInfoPropertyName = "SetIgnoreInputEventsResult")]
[JsonSerializable(typeof(SetInterceptDragsCommandParameters), TypeInfoPropertyName = "SetInterceptDragsCommandParameters")]
[JsonSerializable(typeof(SetInterceptDragsResult), TypeInfoPropertyName = "SetInterceptDragsResult")]
[JsonSerializable(typeof(SynthesizePinchGestureCommandParameters), TypeInfoPropertyName = "SynthesizePinchGestureCommandParameters")]
[JsonSerializable(typeof(SynthesizePinchGestureResult), TypeInfoPropertyName = "SynthesizePinchGestureResult")]
[JsonSerializable(typeof(SynthesizeScrollGestureCommandParameters), TypeInfoPropertyName = "SynthesizeScrollGestureCommandParameters")]
[JsonSerializable(typeof(SynthesizeScrollGestureResult), TypeInfoPropertyName = "SynthesizeScrollGestureResult")]
[JsonSerializable(typeof(SynthesizeTapGestureCommandParameters), TypeInfoPropertyName = "SynthesizeTapGestureCommandParameters")]
[JsonSerializable(typeof(SynthesizeTapGestureResult), TypeInfoPropertyName = "SynthesizeTapGestureResult")]
[JsonSerializable(typeof(CdpEventArgs<DragInterceptedEventArgs>), TypeInfoPropertyName = "DragInterceptedCdpEventArgs")]
[JsonSerializable(typeof(TouchPoint), TypeInfoPropertyName = "InputTouchPoint")]
[JsonSerializable(typeof(GestureSourceType), TypeInfoPropertyName = "InputGestureSourceType")]
[JsonSerializable(typeof(MouseButton), TypeInfoPropertyName = "InputMouseButton")]
[JsonSerializable(typeof(TimeSinceEpoch), TypeInfoPropertyName = "InputTimeSinceEpoch")]
[JsonSerializable(typeof(DragDataItem), TypeInfoPropertyName = "InputDragDataItem")]
[JsonSerializable(typeof(DragData), TypeInfoPropertyName = "InputDragData")]
[JsonSerializable(typeof(global::System.Collections.Generic.IReadOnlyList<TouchPoint>), TypeInfoPropertyName = "IReadOnlyListInputTouchPoint")]
[JsonSerializable(typeof(global::System.Collections.Generic.IReadOnlyList<DragDataItem>), TypeInfoPropertyName = "IReadOnlyListInputDragDataItem")]
[JsonSourceGenerationOptions(
PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
partial class InputJsonSerializerContext : JsonSerializerContext;

/// <summary>
/// Provides static event descriptors for the <see cref="InputDomain"/>.
/// </summary>
public static class InputDomainEvent
{
    /// <summary>
    /// Emitted only when <b>Input.setInterceptDrags</b> is enabled. Use this data with <b>Input.dispatchDragEvent</b> to
    /// restore normal drag and drop behavior.
    /// </summary>
    public static EventDescriptor<CdpEventArgs<DragInterceptedEventArgs>> DragIntercepted { get; } =
        EventDescriptor<CdpEventArgs<DragInterceptedEventArgs>>.Create(
            "goog:cdp.Input.dragIntercepted",
            InputJsonSerializerContext.Default.DragInterceptedCdpEventArgs);

}
